### ISSUE TITLE
Add a "--dry-run" option

### ISSUE THREAD

**Issue by varac** [untitaker/vdirsyncer#131]
so ppl can see what would change first before actually syncing

**Comment by untitaker** [comment]
For anybody who wants to be "careful" when syncing and thinks they want this option, consider putting your collections into git repos and commit after sync.

**Comment by untitaker** [comment]
I don't think I want this in vdirsyncer. The only implementation I can think of would take up the same resources as a normal sync. If you want this for data safety, consider putting your data into a git repository.
