### ISSUE TITLE
Authentication fails after update to vdirsyncer 0.4.1

### ISSUE THREAD

**Issue by Cutuchiqueno** [untitaker/vdirsyncer#165]
I use vdirsyncer with ownCloud 7.0.4 on a webfaction server. After updating vdirsyncer to version 0.4.1 vdirsyncer does authenticate anymore. With former versions there was no problem and I haven't changed configuration. Until now I used a `url = https://oc.[USERNAME].webfactional.com/remote.php/caldav/calendars/[OWNCLOUDUSERNAME]/
` together with `verify = false` and `auth=guess`.

DEBUG output:

```
debug: Using 0 maximal workers.
Discovering collections for pair niels_calendar
debug: GET https://oc.[USERNAME].webfactional.com/.well-known/caldav/
debug: {}
debug: None
debug: Sending request...
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
debug: 302
debug: {'content-length': '242', 'server': 'nginx', 'connection': 'keep-alive', 'location': 'http://oc.[USERNAME].webfactional.com/remote.php/caldav/', 'date': 'Wed, 14 Jan 2015 09:25:36 GMT', 'content-type': 'text/html; charset=iso-8859-1'}
debug: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
debug: <html><head>
debug: <title>302 Found</title>
debug: </head><body>
debug: <h1>Found</h1>
debug: <p>The document has moved <a href="http://oc.[USERNAME].webfactional.com/remote.php/caldav/">here</a>.</p>
debug: </body></html>
debug: PROPFIND http://oc.[USERNAME].webfactional.com/remote.php/caldav/
debug: {'Depth': 0, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: 
debug:         <d:propfind xmlns:d="DAV:">
debug:             <d:prop>
debug:                 <d:current-user-principal />
debug:             </d:prop>
debug:         </d:propfind>
debug:         
debug: Sending request...
debug: 405
debug: {'date': 'Wed, 14 Jan 2015 09:25:36 GMT', 'content-length': '166', 'content-type': 'text/html', 'connection': 'keep-alive', 'server': 'nginx'}
debug: <html>
debug: <head><title>405 Not Allowed</title></head>
debug: <body bgcolor="white">
debug: <center><h1>405 Not Allowed</h1></center>
debug: <hr><center>nginx</center>
debug: </body>
debug: </html>

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/utils.py", line 155, in _discover_from_config
    discovered = list(cls.discover(**config))
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 317, in discover
    for c in d.discover():
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 173, in discover
    for x in self.find_collections():
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 150, in find_collections
    url = self.find_home()
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 133, in find_home
    url = self.find_principal()
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 124, in find_principal
    data=body, is_subpath=False)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 242, in request
    return utils.request(method, url, session=self._session, **more)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/utils/__init__.py", line 239, in request
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 405 Client Error: Not Allowed
critical: Failed to initialize cutuchiqueno_calendar_remote.
```

I notice two things: 1) There is no .well-known folder not in my webfactional root folder and not in the webapp folder for ownCloud (There was none before when it worked). For some reason – maybe related to the former – vdirsyncer is looking for non https urls. This can not work because there is nothing there, it leads to a webfaction service page and thus it is blocked.

I also tried with `verify_fingerprint` but there was no differance in the result.

As I have stated before this happened after updating vdirsyncer to the current version. So there seem to be changes in vdirsyncer I can not or don't know how to workaround.

**Comment by untitaker** [comment]
>debug: <p>The document has moved <a href="http://oc.[USERNAME].webfactional.com/remote.php/caldav/">here</a>.</p>

You did set up well-known URIs somehow, they redirect to the HTTP version of
your site. This is usually done in your nginx config.

well-known URIs have been added in version 0.4.0 -- I did some changes on
version 0.4.1 which make the behavior stricter but also faster. However, it's
IMO a good thing that this problem came up, since it shows a misconfiguration.

**Comment by untitaker** [comment]
Also I strongly recommend you use ``verify_fingerprint = ...`` if your certificate is intentionally invalid.

**Comment by Cutuchiqueno** [comment]
Informed by your hints I figured out that the problem is the default `.htaccess` configuration provided by owncloud itself. There are some redirects which should bridge the change of the url ownCloud made in a former version After I commented these out everything works again.

Since the source of the problem is the owncloud installation itself an more people could be affected, it would maybe good add a comment to the tutorial in the documentation which has ownCloud as its use case.

I am using verify_fingerprint now, thx, you are absolutely right.

**Comment by untitaker** [comment]
Glad to hear that it works!

>Since the source of the problem is the owncloud installation itself an more people could be affected, it would maybe good add a comment to the tutorial in the documentation which has ownCloud as its use case.

I don't know... these redirects are there for a reason, if they redirect to the wrong port/protocol, it's rather a bug in ownCloud. I will have to modify vdirsyncer to deal with such invalid redirects properly again though.

**Comment by Cutuchiqueno** [comment]
yes, I agree it is probably a bug in ownCloud. I just thought it could be helpful in a tutorial using ownCloud as an example (probably a very common situation for vdirsyncer). 

But if you manage vdirsyncer to deal with those situations it's even more perfect ;-) 

Thx!

**Comment by untitaker** [comment]
FWIW, it would be interesting if you managed to actually fix the redirection behavior instead of disabling it. I can't see anything in the .htaccess for 7.0.4 that would cause this bug, which is why I am not sure how it happens on your side.

**Comment by Cutuchiqueno** [comment]
Actually the line that causes the problem is:

```
# RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R]
```

7.0.4 was not the originally installation but the upgrade. I think the original install was 7.0.2 deployed as a webapp automatic  installation provided by webfacitonal.

**Comment by untitaker** [comment]
Ok that line is still there, but for a good reason. I'm not sure if it is either WebFaction or ownCloud who screws up there...
