### ISSUE TITLE
IdentConflict when trying to sync calendars

### ISSUE THREAD

**Issue by hobarrera** [untitaker/vdirsyncer#172]
I've been using `vdirsyncer` to sync contacts for ages. I've now tried to get calendar syncing, but I just can't get past a particular Exception. I've double and triple checked the config, but I can't find out what's wrong:

```ini
[general]
status_path = ~/.local/share/vdirsyncer/status/
password_command = ~/.bin/vdirsyncer-pass

[pair cal_work]
a = cal_work_local
b = cal_work_remote

[storage cal_work_local]
type = filesystem
path = ~/.local/share/calendars/work/
fileext = .ics

[storage cal_work_remote]
type = caldav
# This points to a specific collection:
url = https://calendar.barrera.io/hugo/work/
username = hugo
```

When trying to sync:
```
$ vdirsyncer sync                                 
Discovering collections for pair cal_work
Syncing cal_work
Syncing contacts
Unhandled exception occured while syncing cal_work.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python3.4/site-packages/vdirsyncer/sync.py", line 164, in sync
    b_idents = _prepare_idents(storage_b, storage_a, b_href_to_status)
  File "/usr/lib/python3.4/site-packages/vdirsyncer/sync.py", line 126, in _prepare_idents
    hrefs=[props['href'], other_props['href']])
vdirsyncer.sync.IdentConflict
```

Am I doing something wrong, or is this a bug?

Server logs show nothing wrong.

**Comment by untitaker** [comment]
You have two items with the same UID somewhere... I introduced this check because the previous behavior to ignore one of the items seemed unsafe to me. The dev version should show a much nicer error message about this.

**Comment by hobarrera** [comment]
Ah, thanks. I've verified that this is the case (though I've no idea how I ended up with reused UIDs). I've had to manually fix this on my server, which was not fun either.

If there will be a more understandable message on the following release, then I guess it's safe to close this issue.

Thanks.

**Comment by untitaker** [comment]
I'll leave this open because we kind of leave the user in the wild with making that change serverside.

**Comment by untitaker** [comment]
Anybody got any ideas how we could assist the user in editing UIDs on the server? @hobarrera How did you fix it?

**Comment by hobarrera** [comment]
My fix was not at all user-friendly. I logged onto my server, went to radicale's db directory, and did it manually using `grep`, `uniq`, `sort`, `sed`. and some copy pasting.

It really depends a lot on what server the user has, and what backend that server has (database? plain files?).

I guess some script could be made to do it over CalDAV, but I'd have no idea where to start.

Sorry, I don't think I can help much with this.

**Comment by untitaker** [comment]
Ok so we'd probably have to bake in another CLI command for such cases. Maybe a successor of [``vfix``](https://github.com/geier/vfix).

**Comment by untitaker** [comment]
`vdirsyncer repair cal_work_local` now takes care of this.
