### ISSUE TITLE
Doc missing: How to actually invoke vdirsyncer

### ISSUE THREAD

**Issue by matthiasbeyer** [untitaker/vdirsyncer#174]
The documentation on how to actually _call_ `vdirsyncer` is completely missing... I cannot find how to invoke it...

**Comment by untitaker** [comment]
You mean in the README? The tutorial definetly has it:

    After running ``vdirsyncer sync``, ``~/.contacts/`` will contain a bunch of
    ``.vcf`` files which all contain a contact in ``VCARD`` format each.

**Comment by untitaker** [comment]
I added a short note in the README too.

**Comment by matthiasbeyer** [comment]
Thanks.
