### ISSUE TITLE
Auto-creating directories seems broken

### ISSUE THREAD

**Issue by geier** [untitaker/vdirsyncer#179]
I'm running the latest version of vdirsyncer and it does not auto-create directories:

    error: No collection abook found for storage home_contacts_local.
	Should vdirsyncer attempt to create it? [y/N]: y
	Syncing contacts/abook
	debug: Loaded status for contacts/abook
	error: Directory /home/cg/.contacts/abook does not exist.
	error: No collection None found for storage home_contacts_local.
	Should vdirsyncer attempt to create it? [y/N]: y
	error: Directory /home/cg/.contacts/abook does not exist.
	Unhandled exception occured for contacts/abook.
	Traceback (most recent call last):
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/tasks.py", line 67, in sync_collection
	    a = storage_instance_from_config(config_a)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/utils.py", line 418, in storage_instance_from_config
	    return storage_instance_from_config(config, create=False)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/utils.py", line 413, in storage_instance_from_config
	    return cls(**new_config)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/storage/filesystem.py", line 46, in __init__
	    checkdir(path, create=False)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/utils/__init__.py", line 330, in checkdir
	    .format(path))
	CollectionNotFound: Directory /home/cg/.contacts/abook does not exist.

**Comment by untitaker** [comment]
Does ``.contacts`` exist? Will take a look later.

**Comment by geier** [comment]
yes, created that by hand when vdirsyncer didn't create it.

**Comment by untitaker** [comment]
I am unable to reproduce this, but I do see some theoretical issues in the code.

**Comment by untitaker** [comment]
Fixed several bugs in master. I haven't been able to reproduce them, but basically the prompts during *discovery* were handled separately from the promts that happen during *sync*. Could you check again with master?

**Comment by geier** [comment]
different, but not good yet:

	(git)[master|✔ ]% vdirsyncer -v DEBUG sync --max-workers 1 contacts                                              ~/workspace/vdirsyncer
	debug: Using 1 maximal workers.
	Syncing contacts/abook
	debug: Loaded status for contacts/abook
	error: Directory /home/cg/.contacts/abook does not exist.
	error: No collection abook found for storage home_contacts_local.
	Should vdirsyncer attempt to create it? [y/N]: y
	Unhandled exception occured for contacts/abook.
	Traceback (most recent call last):
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/tasks.py", line 67, in sync_collection
	    a = storage_instance_from_config(config_a)
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/utils.py", line 419, in storage_instance_from_config
	    config, config.get('collection', None), e=str(e))
	  File "/home/cg/workspace/vdirsyncer/vdirsyncer/cli/utils.py", line 198, in _handle_collection_not_found
	    args = cls.create_collection(collection=collection, **config)
	TypeError: create_collection() got multiple values for keyword argument 'collection'
	1

**Comment by untitaker** [comment]
I have no idea what I am doing. Try now?

**Comment by untitaker** [comment]
Argh, found another bug, something with mutable state. >.<

**Comment by untitaker** [comment]
*There we go, please try again.*

**Comment by geier** [comment]
this only occurred when paths were given relative to a user's home (with `~/`)

**Comment by untitaker** [comment]
Ah, got it.
