### ISSUE TITLE
Exclude collections from syncronization

### ISSUE THREAD

**Issue by shervin86** [untitaker/vdirsyncer#184]
The special values "from a" and "from b" in the "collections" field is very useful. 
It would be nice to have a way to exclude specific collections, like:
```
[pair zimbra_calendar]
a = zimbra_calendar_local
b = zimbra_caldav_remote
collections = ["from b" "!work" ]
```
where all the collections in b are downloaded except the one that is called "work"

**Comment by untitaker** [comment]
I don't think I want this functionality, at least as long as it's not requested multiple times.

The collections parameter originally didn't have "from a" or "from b". These parameters were only added for the particular purpose of syncing all collections. It was also intended for cases where people didn't know the collection names. I don't really want to add complex black/whitelisting or set operations to the config syntax.

Do this instead:

  1.  Run `vdirsyncer discover`. It will discover all collections, and give you all their names.
  2. Paste the collection names into your config.

**Comment by c-schwamborn** [comment]
I could also use this feature as I'm undertaking a huge migration at my University where i need to expunge some unwanted calendars present in every principal. The suggestion above with `vdirsyncer discover` is quite unpractical in this case.
