### ISSUE TITLE
Handle iCalendar parsing errors gracefully

### ISSUE THREAD

**Issue by mbaldessari** [untitaker/vdirsyncer#185]
Hi Markus,

here is a traceback a user got when fetching his trip_it event list. Maybe it is a tripit encoding, issue
but it'd be nice not to crash:
```
Syncing my_tripit
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:747: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html   InsecureRequestWarning)
Unhandled exception occured for my_tripit.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 72, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 158, in sync
    b_idents = _prepare_idents(storage_b, storage_a, b_href_to_status)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 113, in _prepare_idents
    hrefs = _prepare_hrefs(storage, other_storage, href_to_status)
  File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 98, in _prepare_hrefs
    for href, etag in storage.list():
  File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/http.py", line 114, in list
    for item in split_collection(r.text):
  File "/usr/lib/python2.7/site-packages/vdirsyncer/utils/vobject.py", line 129, in split_collection
    collections = icalendar.cal.Component.from_ical(text, multiple=True)
  File "/usr/lib/python2.7/site-packages/icalendar/cal.py", line 301, in from_ical
    name, params, vals = line.parts()
  File "/usr/lib/python2.7/site-packages/icalendar/parser.py", line 326, in parts
    % (self, exc)
ValueError: Content line could not be parsed into parts: u'\\n602 00 Brno': \n602 00 Brno
```

I believe the culprit line is the following:
```
LOCATION:Kounicova 6^M\n602 00 Brno
```

Hope this helps and let me know if you need more info.

Thanks for vdirsyncer,
Michele

**Comment by untitaker** [comment]
Yeah, that seems like a bad continuation line. Vdirsyncer shouldn't crash because of this, but other than showing an error there's not much I can do.

**Comment by mathstuf** [comment]
Just an FYI, I've seen errors using CalDAV-Sync on Android with Google where they gave a bad datestamp (something like `20121020T130` where the time was missing a zero).

**Comment by untitaker** [comment]
I'm seriously considering forking icalendar and ripping out all functionality I don't need. So vdirsyncer would be able to sync partially invalid items because it doesn't really care if they're valid.

The better solution would be to introduce proper lazy parsing into icalendar.

**Comment by untitaker** [comment]
First efforts in https://github.com/untitaker/vdirsyncer/commit/6dac27d741486bccd6f368cc728f61af74d1761b, although that one is rather for performance reasons.

**Comment by untitaker** [comment]
Could you guys check with the latest git version? It should be much faster and not crash on those items (you'll get a similar error when khal tries to read those items though).

**Comment by mbaldessari** [comment]
Let me check with the user that reported this and get back to you. Thanks!

**Comment by mbaldessari** [comment]
Confirmed as fixed. Thanks again

**Comment by untitaker** [comment]
>the user that reported this

Just found out that there's a Fedora package for vdirsyncer. I'd like to link it [in the documentation](http://vdirsyncer.readthedocs.org/en/stable/tutorial.html#installation) but am unsure which link to use?

**Comment by mathstuf** [comment]
On Wed, Mar 11, 2015 at 08:14:57 -0700, Markus Unterwaditzer wrote:
> Just found out that there's a Fedora package for vdirsyncer. I'd like
> to link it [in the
> documentation](http://vdirsyncer.readthedocs.org/en/stable/tutorial.html#installation)
> but am unsure which link to use?

https://admin.fedoraproject.org/pkgdb/package/vdirsyncer/

**Comment by mathstuf** [comment]
On Wed, Mar 11, 2015 at 11:43:20 -0400, Ben Boeckel wrote:
> https://admin.fedoraproject.org/pkgdb/package/vdirsyncer/

Alternatively, https://apps.fedoraproject.org/packages/vdirsyncer

**Comment by mbaldessari** [comment]
What mathstuf saidd. It will hit Fedora 22 once it is released (i.e. yum install vdirsyncer will work out of the box)

**Comment by untitaker** [comment]
Thanks! Added.

**Comment by untitaker** [comment]
Ah ok, didn't know that that version isn't released yet. I'll keep it anyway.

**Comment by mbaldessari** [comment]
Yeah I have built a temporary package with git head for the user to test and he confirmed it works. Once vdirsyncer gets a new release I will make sure Fedora gets updated packages as well
