### ISSUE TITLE
missing VERSION error when syncing to Apple OSX Calendar server

### ISSUE THREAD

**Issue by rasca-artcom** [untitaker/vdirsyncer#194]
While trying to use vdirsyncer to sync with an Apple OSX Calendar server I see the error

    <error-description xmlns='http://twistedmatrix.com/xml_namespace/dav/'><![CDATA[Can't parse calendar data: iCalendar missing VERSION: 
    debug: BEGIN:VCALENDAR
    debug: BEGIN:VEVENT
    debug: DTEND;TZID=Europe/Berlin:20150218T154500
    [..]
    debug: END:VEVENT
    debug: END:VCALENDAR
    debug: ]]></error-description>
    debug: </error>

But the original local ICS file contains a "VERSION:2.0" line.
Tested under Ubuntu 14.04 with vdirsyncer 0.4.1 and 0.4.4

**Comment by untitaker** [comment]
Could you post the full traceback?

**Comment by rasca-artcom** [comment]
vdirsyncer -v DEBUG sync
debug: Using 0 maximal workers.
Syncing user_calendar
debug: Loaded status for user_calendar
debug: REPORT https://xclient.intern.artcom.de/calendars/users/mustermann/calendar/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <C:calendar-query xmlns:D="DAV:"
debug:                 xmlns:C="urn:ietf:params:xml:ns:caldav">
debug:                 <D:prop>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:                 <C:filter>
debug:                 <C:comp-filter name="VCALENDAR"/>
debug:                 </C:filter>
debug:             </C:calendar-query>
debug: Sending request...
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
debug: 207
debug: {'content-length': '441', 'accept-ranges': 'bytes', 'strict-transport-security': 'max-age=604800', 'vary': 'User-Agent', 'keep-alive': 'timeout=15, max=100', 'ms-author-via': 'DAV', 'server': 'Twisted/13.2.0 TwistedWeb/9.0.0', 'last-modified': 'Wed, 15 Apr 2015 08:20:38 GMT', 'connection': 'Keep-Alive', 'etag': '"c08e7a6d645778d559bcc7a2874a14b5"', 'dav': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-availability, inbox-availability, calendar-proxy, calendarserver-private-events, calendarserver-private-comments, calendarserver-sharing, calendarserver-sharing-no-scheduling, calendar-query-extended, calendar-default-alarms, calendar-managed-attachments, calendarserver-partstat-changes, calendar-no-timezone, calendarserver-recurrence-split, addressbook, extended-mkcol, calendarserver-principal-property-search, calendarserver-principal-search, calendarserver-home-sync', 'date': 'Wed, 15 Apr 2015 17:23:15 GMT', 'x-frame-options': 'SameOrigin', 'content-type': 'text/xml'}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/calendars/users/mustermann/calendar/3382b02d1ab71aaf660934a4682b8cc8-b3e9c5aa.ics</href>
debug:     <propstat>
debug:       <prop>
debug:         <getcontenttype>text/calendar;charset=utf-8</getcontenttype>
debug:         <getetag>"514cae3ee58773345436c5a4d862ade5"</getetag>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: REPORT https://xclient.intern.artcom.de/calendars/users/mustermann/calendar/
debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:         <C:calendar-multiget xmlns:D="DAV:"
debug:             xmlns:C="urn:ietf:params:xml:ns:caldav">
debug:             <D:prop>
debug:                 <D:getetag/>
debug:                 <C:calendar-data/>
debug:             </D:prop>
debug:             <D:href>/calendars/users/mustermann/calendar/3382b02d1ab71aaf660934a4682b8cc8-b3e9c5aa.ics</D:href>
debug:         </C:calendar-multiget>
debug: Sending request...
debug: 207
debug: {'content-length': '1322', 'accept-ranges': 'bytes', 'strict-transport-security': 'max-age=604800', 'vary': 'User-Agent', 'keep-alive': 'timeout=15, max=99', 'ms-author-via': 'DAV', 'server': 'Twisted/13.2.0 TwistedWeb/9.0.0', 'last-modified': 'Wed, 15 Apr 2015 08:20:38 GMT', 'connection': 'Keep-Alive', 'etag': '"c08e7a6d645778d559bcc7a2874a14b5"', 'dav': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-availability, inbox-availability, calendar-proxy, calendarserver-private-events, calendarserver-private-comments, calendarserver-sharing, calendarserver-sharing-no-scheduling, calendar-query-extended, calendar-default-alarms, calendar-managed-attachments, calendarserver-partstat-changes, calendar-no-timezone, calendarserver-recurrence-split, addressbook, extended-mkcol, calendarserver-principal-property-search, calendarserver-principal-search, calendarserver-home-sync', 'date': 'Wed, 15 Apr 2015 17:23:15 GMT', 'x-frame-options': 'SameOrigin', 'content-type': 'text/xml'}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/calendars/users/mustermann/calendar/3382b02d1ab71aaf660934a4682b8cc8-b3e9c5aa.ics</href>
debug:     <propstat>
debug:       <prop>
debug:         <getetag>"514cae3ee58773345436c5a4d862ade5"</getetag>
debug:         <calendar-data xmlns='urn:ietf:params:xml:ns:caldav'><![CDATA[BEGIN:VCALENDAR
debug: VERSION:2.0
debug: PRODID:-//CALENDARSERVER.ORG//NONSGML Version 1//EN
debug: BEGIN:VEVENT
debug: UID:3843af98-9d6d-4814-a039-06569fd6bbc9
debug: DTSTART;TZID=Europe/Berlin:20150218T141500
[..]
debug: END:VEVENT
debug: END:VCALENDAR
debug: ]]></calendar-data>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
Doing conflict resolution for item 3843af98-9d6d-4814-a039-06569fd6bbc9...
...user_calendar_local wins.
Copying (updating) item 3843af98-9d6d-4814-a039-06569fd6bbc9 to user_calendar_remote
debug: PUT https://xclient.intern.artcom.de/calendars/users/mustermann/calendar/3382b02d1ab71aaf660934a4682b8cc8-b3e9c5aa.ics
debug: {'Content-Type': 'text/calendar', 'If-Match': u'"514cae3ee58773345436c5a4d862ade5"', 'User-Agent': 'vdirsyncer'}
debug: BEGIN:VCALENDAR
debug: BEGIN:VEVENT
debug: UID:3843af98-9d6d-4814-a039-06569fd6bbc9
debug: DTSTART;TZID=Europe/Berlin:20150218T141500
[..]
debug: END:VEVENT
debug: END:VCALENDAR
debug: Sending request...
debug: 403
debug: {'content-length': '1020', 'strict-transport-security': 'max-age=604800', 'vary': 'User-Agent', 'keep-alive': 'timeout=15, max=98', 'ms-author-via': 'DAV', 'server': 'Twisted/13.2.0 TwistedWeb/9.0.0', 'connection': 'Keep-Alive', 'dav': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-availability, inbox-availability, calendar-proxy, calendarserver-private-events, calendarserver-private-comments, calendarserver-sharing, calendarserver-sharing-no-scheduling, calendar-query-extended, calendar-default-alarms, calendar-managed-attachments, calendarserver-partstat-changes, calendar-no-timezone, calendarserver-recurrence-split, addressbook, extended-mkcol, calendarserver-principal-property-search, calendarserver-principal-search, calendarserver-home-sync', 'date': 'Wed, 15 Apr 2015 17:23:15 GMT', 'x-frame-options': 'SameOrigin', 'content-type': 'text/xml'}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <error xmlns='DAV:'>
debug:   <valid-calendar-data xmlns='urn:ietf:params:xml:ns:caldav'/>
debug:   <error-description xmlns='http://twistedmatrix.com/xml_namespace/dav/'><![CDATA[Can't parse calendar data: iCalendar missing VERSION: 
debug: BEGIN:VCALENDAR
debug: BEGIN:VEVENT
debug: DTEND;TZID=Europe/Berlin:20150218T154500
debug: UID:3843af98-9d6d-4814-a039-06569fd6bbc9
debug: DTSTART;TZID=Europe/Berlin:20150218T141500
[..]
debug: END:VEVENT
debug: END:VCALENDAR
debug: ]]></error-description>
debug: </error>
Unhandled exception occured for user_calendar.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/cli/tasks.py", line 70, in sync_collection
    force_delete=force_delete
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/sync.py", line 171, in sync
    action(a_info, b_info, conflict_resolution)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/sync.py", line 272, in inner
    _action_update(ident, a, b)(a, b, conflict_resolution)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/sync.py", line 216, in inner
    dest_meta['etag'])
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/dav.py", line 439, in update
    href, etag = self._put(self._normalize_href(href), item, etag)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/dav.py", line 427, in _put
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/storage/dav.py", line 236, in request
    return utils.request(method, url, session=self._session, **more)
  File "/usr/local/lib/python2.7/dist-packages/vdirsyncer/utils/__init__.py", line 255, in request
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden

**Comment by untitaker** [comment]
You'd need to use `--max-workers=1` to be sure, but it doesn't seem like your uploaded item contains any VERSION property. I can't do anything against your server requiring that one.

**Comment by rasca-artcom** [comment]
In the original local file there *is* a VERSION entry. For me it looks like the vdirsyncer parses the local ICS file and the resulting ICS in memory does not contain VERSION anymore.

**Comment by untitaker** [comment]
It seems to me that only some of your entries contain a VERSION property.

Are you using singlefile- or filesystem-storage locally? In the case of filesystem-storage, we copy the raw string to the server and don't do any parsing, so it's very unlikely that vdirsyncer would drop the version property.

**Comment by rasca-artcom** [comment]
It's a single file storage.

**Comment by untitaker** [comment]
@rasca-artcom This should be fixed in master. Try this:

    pip install --user --force-reinstall https://github.com/untitaker/vdirsyncer.git

**Comment by untitaker** [comment]
@rasca-artcom Does the fix work for you?

**Comment by rasca-artcom** [comment]
Thanks for the work. The command above did not update - I had to add "--upgrade" to get the installation run through.
When I run the vdirsyncer now it looks like the problem is fixed. I don't see an error about the VERSION attribute. Thx.

**Comment by untitaker** [comment]
You're welcome!
