### ISSUE TITLE
Disallow verify = false

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#196]
in response to #195

**Comment by geier** [comment]
why is verify = false worse than plain http?

**Comment by untitaker** [comment]
From a security perspective it's only slightly worse, because the user might wrongly assume that their traffic is encrypted, when in fact it's not. From a performance perspective it adds nearly-useless encryption overhead.

I think you wanted to argue that vdirsyncer could forbid plain HTTP by the same reasoning, but the idea I had was rather: If you already have some SSL-stack in place, even with an invalid certificate, it's always a better idea to use `verify_fingerprint` than disabling verification altogether.

**Comment by untitaker** [comment]
Of course that train-of-thought wasn't really obvious, so vdirsyncer would advise the user on how to use `verify_fingerprint` in its error message when the user would try to use `verify = false`.
