### ISSUE TITLE
Unexpected keyword argument 'buffering' when syncing

### ISSUE THREAD

**Issue by thomwiggers** [untitaker/vdirsyncer#198]
I'm getting this error when I sync with OwnCloud: 

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/reTraceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
        httplib_response = conn.getresponse(buffering=True)
    TypeError: getresponse() got an unexpected keyword argument 'buffering'quests/packages/urllib3/connectionpool.py", line 372, in _make_request
        httplib_response = conn.getresponse(buffering=True)
    TypeError: getresponse() got an unexpected keyword argument 'buffering'

**Comment by untitaker** [comment]
Downgrade requests to `2.6.0`, this is https://github.com/shazow/urllib3/issues/598

**Comment by untitaker** [comment]
Closing as duplicate of #195
