### ISSUE TITLE
Double URL-encoding on python 3.

### ISSUE THREAD

**Issue by t-8ch** [untitaker/vdirsyncer#203]
Vdirsyncer version: eec503b (latest master)

When syncing with my horde server the href in the `calendar-multiget` REPORT query ends up being urlencoded two times:

Python2:
```
<D:href>/horde/rpc/calendars/t-8ch/calendar%3AYYYYYYYY/XXXXXX.ics</D:href>
```
Python3:
```
<D:href>/horde/rpc/calendars/t-8ch/calendar%253AYYYYYYY/XXXXXX.ics</D:href>
```

Because of this the server does not find the specified calendar and vdirsyncer exits with `NotFound`.

I try to fix this later.

**Comment by untitaker** [comment]
This might be a bug in the way vdirsyncer does collection discovery -- the code which accesses the `.collections` status files might make different assumptions about whether the values are encoded.

**Comment by untitaker** [comment]
I'm completely baffled regarding the different behavior of Python 2 vs 3.

**Comment by t-8ch** [comment]
@untitaker I am also buffled :-). I could create an account for you in my Horde instance.

**Comment by untitaker** [comment]
Yes please, but I'm not sure what to look for.

**Comment by t-8ch** [comment]
@untitaker Sent you the info via mail. The problem also happen when syncing contacts.

**Comment by untitaker** [comment]
I've tried it out -- sync works fine for what appears to be the main
addressbook, but I manage to generate Internal Server Errors when syncing the
"Favorites"-list.

I'd be interested in putting Horde into CI -- are the system requirements
complicated?

**Comment by t-8ch** [comment]
Did you configure a baseurl or the URL to a specific collection?

It should be fairly easy with apache and a database. (My setup is rather old).

**Comment by untitaker** [comment]
I let vdirsyncer autodiscover everything. The collections found are
"contacts:favourites" and "contacts~5sEJbpfZH6t_7cAZl4aDHi1".

**Comment by t-8ch** [comment]
Hm, another weird thing is that vdirsyncer detects an event incorrectly as changed and tries to upload it, then breaks on this. (The misdetected event changes on each run)

**Comment by untitaker** [comment]
Are these issues specific to Python 3?

**Comment by t-8ch** [comment]
Yes, I have two brandnew venvs on the same source checkout. Py3 never works, Py2 always.

**Comment by untitaker** [comment]
I'll try with Py3, was unintentionally using Python 2.

**Comment by t-8ch** [comment]
Hm, looking at my logs, your internal ids are of the form: `calendar~foo` while mine are `calendar:foo`.

**Comment by t-8ch** [comment]
Except your `calendar:favourites`, which crash it completely...

**Comment by t-8ch** [comment]
My new addressbook also use tildes. Brb, messing with the database.

**Comment by untitaker** [comment]
It occured to me that vdirsyncer incorrectly detects changes on a local filesystem-storage after having switched from Python 2 to 3 or other way round. I probably won't fix this, since a simple fix would remove quite some precision from the mtime detection (which might cause vdirsyncer to miss changes).

**Comment by t-8ch** [comment]
@untitaker But it shouldn't break, should it?
I now updated the ID of your calendar to include the colon instead of the tilde, care to retry?

**Comment by t-8ch** [comment]
Btw: the discovery feature seems not to use the default http infrastructure (at least it has the default requests useragent string)

**Comment by untitaker** [comment]
I still hit the 500-server-error:

    debug: PROPFIND [...]/rpc/addressbooks/untitaker/contacts:favourites/
    debug: {'User-Agent': 'vdirsyncer', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': 1}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:propfind xmlns:D="DAV:">
    debug:                 <D:prop>
    debug:                     <D:resourcetype/>
    debug:                     <D:getcontenttype/>
    debug:                     <D:getetag/>
    debug:                 </D:prop>
    debug:             </D:propfind>
    debug:             
    debug: Sending request...
    debug: 500
    [...]
    debug: b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>Sabre\\DAV\\Exception</s:exception>\n  <s:messa
    ge>No source for favourite recipients exists.</s:message>\n  <s:sabredav-version>1.8.10</s:sabredav-version>\n</d:error>\n'
    Unhandled exception occured for contacts/contacts:favour

**Comment by t-8ch** [comment]
I never did the discovery thing, so I never saw this.

**Comment by untitaker** [comment]
The UA-bug should be fixed as of latest master.

**Comment by t-8ch** [comment]
I don't see any differences between our data, except the autodiscovery stuff. No idea how this could affect anything, but could you try an explicit URL for the calendar?

**Comment by t-8ch** [comment]
And maybe create local differences which will be synced.

**Comment by t-8ch** [comment]
Here you have it :-)

**Comment by untitaker** [comment]
I tried all of that -- I created and edited events through the webinterface, deleted and edited data locally. I now tried the direct calendar-URL, no difference. The only problem I encounter is that my favourited contacts create server errors.

**Comment by untitaker** [comment]
Interesting, changing the item locally actually produces a NotFoundError. However, after syncing a second time, the error disappears and vdirsyncer continues to operate normally.

**Comment by untitaker** [comment]
Ahh, this is in a completely different part than I thought: This is happening inside `update`'s invocation of `get_multi`.

**Comment by t-8ch** [comment]
Did it actually sync? So if this is a onetime problem it gets multiplied by my py2 -> py3 switch.
Ah, I get the same on python2 when updating locally (which I normally never do).
So this is independent from the python version.

**Comment by untitaker** [comment]
Check out https://github.com/untitaker/vdirsyncer/pull/204, it should fix everything. Make sure your collections are somewhat in sync though, this one will trigger sync conflicts for *every item*.

**Comment by t-8ch** [comment]
@untitaker Seems to work fine! Thanks!
(I'll delete your Horde account and investigate in adding Horde to the Ci infrastructure this weekend)

**Comment by untitaker** [comment]
I've merged the PR with some minor modifications. Regarding CI: Even the current setup for ownCloud with sqlite is very heavyweight, as ownCloud itself is incredibly slow. I am not sure if Travis could handle that.

**Comment by untitaker** [comment]
I've had to revert the fix, I'm now trying a simpler one. @t-8ch Could you try https://github.com/untitaker/vdirsyncer/pull/205?

**Comment by t-8ch** [comment]
@untitaker Seems to work!
