### ISSUE TITLE
icloud sync seems broken again

### ISSUE THREAD

**Issue by maxandersen** [untitaker/vdirsyncer#206]
Hey in #95 we got icloud syncing fixed.

But now it seems broken again - I haven't been using vdirsyncer for a while so can't say exactly when.

But for now I only get the directories for each calendar/reminder I have - no actual .ics files are created.

Config is like this:

```

[general]
# A folder where vdirsyncer can store some metadata about each pair.
status_path = ~/.vdirsyncer/status/

# CALDAV
[pair reminders]
a = reminders_local
b = reminders_remote
collections = ["from b"]

[storage reminders_local]
type = filesystem
path = ~/.calendars/
fileext = .ics

[storage reminders_remote]
type = caldav
url = https://p01-caldav.icloud.com:443/199120242/calendars/
username = apple@blah.blah
password = secrect
```

**Comment by untitaker** [comment]
It's working fine for me. Which commit hash are you using?

**Comment by maxandersen** [comment]
I installed via pip.

Version I got is "vdirsyncer, version 0.4.4"

**Comment by untitaker** [comment]
Ahh, I know what's wrong: set `item_types = []` for caldav. The latest git version does work, because that value is the default there.

**Comment by maxandersen** [comment]
that made no difference. I still just get the dir structure - no actual content.

**Comment by untitaker** [comment]
Could you try with the URL recommended [in the docs](https://vdirsyncer.readthedocs.org/en/stable/supported.html#icloud)? If that doesn't work, please send me a debug log of everything.

**Comment by maxandersen** [comment]
note, just cloned git repo and ran `make install`, *then* it works. So seems to be something beyound just item_types.

**Comment by untitaker** [comment]
`make install` isn't supposed to do anything at all.

**Comment by maxandersen** [comment]
sorry - just `make`

**Comment by untitaker** [comment]
*Don't do that*, `make` does a lot more than installing or building vdirsyncer. I'll take a look at how to fix the Makefile.

I have no idea what changed, but it seems like this is resolved.

**Comment by maxandersen** [comment]
Okey, but readme doesn't actually state which command to run to build it from source so I took a guess ;)

**Comment by untitaker** [comment]
Installation is not that easy. `pip install .` usually works, but after that, there's no clean way to remove vdirsyncer fully. I've updated the Makefile to link to the relevant docs.
