### ISSUE TITLE
Invalid character in vcard results in unhandled exception

### ISSUE THREAD

**Issue by tomka** [untitaker/vdirsyncer#207]
A vcard on my DAViCal server contains a character that is apparently not legal for vdirsyncer: It causes an `InvalidXMLResponse` error and vdirsyncer closes itself. It would be nicer if an error could be generated, but all other contacts would be synced. Or alternatively, if the user is given the option to replace this character, abort, or ignore it. Evolution ignores such characters and just shows an equals sign.

The character that causes this is shown as `^P` in vim and is part of the NOTE section. Pressing `ga` to get the ASCII representation gives `<^P>  16,  Hex 10,  Octal 020`. The encoding of the XML document is UTF-8.

I get the following strack trace in this situation:

    Unhandled exception occured for my_contacts.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 70, in sync_collection
        force_delete=force_delete
      File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 159, in sync
        b_info.prepare_idents(storage_a.read_only)
      File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 114, in prepare_idents
        hrefs_to_download else ()):
      File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 384, in get_multi
        root = _parse_xml(response.content)  # etree only can handle bytes
      File "/usr/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 50, in _parse_xml
        .format(e))
    InvalidXMLResponse: Invalid XML encountered: PCDATA invalid Char value 16, line 5512, column 30
    Double-check the URLs in your config.

**Comment by untitaker** [comment]
Could you give me the Content-Type header of the response? It also might be a different encoding than expected.

**Comment by untitaker** [comment]
I've got a PR prepared for this (it skips the broken character) but I'd like to still know what the encoding was. This might be the wrong fix for your issue.

**Comment by tomka** [comment]
Hi, the `Content-Type` header is `text/xml charset="utf-8"`. And  the encoding of the XML data sent is UTF-8.

**Comment by untitaker** [comment]
Ok great, so #208 should be appropriate.

Could you try:

    pip install --user --force-reinstall -U git+https://github.com/untitaker/vdirsyncer@tolerant-xml-parser

?

**Comment by tomka** [comment]
Thanks, I installed vdirsyncer in a virtualenv and started it from there, this should work the same. After I managed to insert this character again (by copying it directly into the VCF file, vdirsyncer sent the odd character without problems), I was able to try again. This time the invalid character is handled gracefully:

    warning: Partially invalid XML response: <string>:20:32:FATAL:PARSER:ERR_INVALID_CHAR: PCDATA invalid Char value 16

Very nice, thanks for looking into this so quickly!  It would be even more helpful, if the item ID would be part if the warning so that one can manually investigate the situation.

And as it seems to me you just skip this character and thereby changing the item, correct? At least I can't see the invalid character in the produced VCF file anymore. Is this change uploaded (or copied to the other storage) as well?

**Comment by untitaker** [comment]
> Very nice, thanks for looking into this so quickly!  It would be even more helpful, if the item ID would be part if the warning so that one can manually investigate the situation.

I don't think that's possible.
> 
> And as it seems to me you just skip this character and thereby changing the item, correct?

Yup.

> At least I can't see the invalid character in the produced VCF file anymore. Is this change uploaded (or copied to the other storage) as well?

That depends on the local storage.

- On singlefile-storage, yes, a second sync will upload the new item
  immediately.

- On filesystem-storage, the item with the skipped chars will be uploaded once
  you make explicit changes to it.
