### ISSUE TITLE
Cannot update event with UID collision

### ISSUE THREAD

**Issue by geier** [untitaker/vdirsyncer#212]
Using vdirsyncer's FilesystemStorage I run into a problem when trying to upload/new a new item.

If an VEVENT with the same UID as the VEVENT I want to create already exists, I get an AlreadyExistingError but I have no chance (using FilesystemStorage's public API) to find out the href of the item with the same uid (nor its etag).

I would suggest to either add an `overwrite()` or an `get_href(uid)` method.

**Comment by untitaker** [comment]
Is this occuring with normal sync, or by calling the interface through khal? Sync should show an extremely helpful error message, and AlreadyExistingError should never be raised.

**Comment by geier** [comment]
by calling the interface through khal. I've used [this workaround](https://github.com/geier/khal/commit/eb8b79e3c6a36639c0ee145c0fc936053003a013#diff-4240f1d60d21cf5fae38cb1e216636fcR147) for the moment.

**Comment by untitaker** [comment]
Hmm, why do you want to overwrite components in the first place? This seems like a very dangerous thing to do when other processes are writing to the vdir at the same time.

**Comment by geier** [comment]
My use case here is the new import function. Import an event, import an updated version later. Some user interaction might be advisable, but I still might  want to overwrite that event.

**Comment by untitaker** [comment]
`self.update(href, item, self.get(...)[1])` seems like a slightly better hack to me.

What you could also do is to load the existing event and check if its sequence number is larger or equal to the new event. If yes, you'll probably want to ask the user.

**Comment by geier** [comment]
The problem is, I do not know the events href, only its uid (which might no be the same).

Checking for the sequence number is probably a good idea.

**Comment by untitaker** [comment]
Argh, I forgot. I've pushed a commit which should give you the existing href in form of an attribute on the exception.

**Comment by geier** [comment]
awesome, this will do.
