### ISSUE TITLE
Read-only (public) calendars?

### ISSUE THREAD

**Issue by clauseggers** [untitaker/vdirsyncer#222]
As far as I can gather, adding authentication-less (public) read-only caldav calendars to vdirsyncer is not possible. It would be a neat feature to have this functionality within virdirsyncer.

Examples are the Facebook events calendar, public calendars of various countries' public holidays, and other such private or public - but read-only - calendars.

It would be neat to have a special section for such read-only calendars, so that I could simply add a list of these URLs under that section.

So far I have only tried to setup a sync on the Facebook events caldav, but the parser gave up on that particular calendar. I can however open the feed in a browser and see the contents in an editor.

**Comment by clauseggers** [comment]
I should RTFM.
https://vdirsyncer.readthedocs.org/en/latest/config.html?highlight=type#read-only-storages

**Comment by untitaker** [comment]
Floating-point exit codes don't make sense, also this will trigger probably unexpected behavior with strings like "0xfff".

**Comment by untitaker** [comment]
Sorry, replied to wrong email!

You want the HTTP storage type. If you can download a file with the browser, it has almost certainly nothing to do with DAV.

That storage is indeed marked as `read_only`: Any local changes will be reverted within a few syncs.

**Comment by clauseggers** [comment]
Yup, discovered that after I had posted. Doh. You are welcome to delete this thread.
