### ISSUE TITLE
Some SSL broke when I got on latest build of OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by clauseggers** [untitaker/vdirsyncer#224]
I have a cronjob that syncs my calendars, and it worked fine until yesterday when I updated to the latest version of OpenSUSE Tumbleweed (now compiled with GCC 5). I can see that most likely something changed that broke the Python SSL:

```
Unhandled exception occured for my_facebook_events.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 267, in ssl_w
rap_socket
    context.load_verify_locations(ca_certs)
IsADirectoryError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:
```
(and then a whole lot of stuff that broke because of the above error)

Do you have ideas on what I should check?

**Comment by untitaker** [comment]
Is python-requests installed via an OpenSUSE package? I've heard about a
similar problem with OpenSUSE, I'm pretty sure it's their fault.

In the docs there is a section called manual installation -- you might want to
use that instead of installing vdirsyncer globally.
https://vdirsyncer.readthedocs.org/en/stable/problems.html#manual-installation

If that doesn't help, pin your certificate by fingerprint:
https://vdirsyncer.readthedocs.org/en/latest/ssl-tutorial.html#pinning-by-fingerprint

**Comment by t-8ch** [comment]
Blind guess: They patched to default certificate location to point to a cert dir instead of a single bundle.

@clauseggers Can you execute

```sh
$ file $(python -c 'import requests; print(requests.certs.where())')
```

**Comment by clauseggers** [comment]
I think you are on to something – I get this output when executing your command:
`/etc/ssl/certs/: directory`

**Comment by t-8ch** [comment]
So downstream patched this. Please bring it up with them.

**Comment by clauseggers** [comment]
@untitaker I tried first to pin the facebook feed, but I got this then:
```
Unhandled exception occured for my_facebook_events.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 367, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 242, in connect
    self.assert_fingerprint)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 127, in assert_fingerprint
    raise SSLError('Fingerprint is of invalid length.')
requests.packages.urllib3.exceptions.SSLError: Fingerprint is of invalid length.
```
(errors continue…)

**Comment by t-8ch** [comment]
@clauseggers Then you got the wrong fingerprint :-)
Either an unsupported algorithm or a typo.

**Comment by clauseggers** [comment]
@t-8ch Will do, thanks.

**Comment by clauseggers** [comment]
@t-8ch Hmm. I tried both the SH1 and MD5 I got from looking in the browser cert. I have these for https://www.facebook.com:
```
35:82:52:AB:83:A5:DD:F0:1F:6B:80:E2:CB:5B:AC:5A
81:AB:B5:70:3A:0A:39:EA:1A:6C:BB:1F:B6:8E:09:AE:16:CB:B2:51
```

Do you get the the same result (if you don’t mind looking).

**Comment by t-8ch** [comment]
This works:
```py
import requests
from requests_toolbelt.adapters.fingerprint import FingerprintAdapter

facebook_fingerprint = '81:AB:B5:70:3A:0A:39:EA:1A:6C:BB:1F:B6:8E:09:AE:16:CB:B2:51'
facebook_fingerprint = '35:82:52:AB:83:A5:DD:F0:1F:6B:80:E2:CB:5B:AC:5A'
s = requests.Session()
s.mount(
    'https://facebook.com',
    FingerprintAdapter(facebook_fingerprint)
)

print(s.get('https://facebook.com/'))
```

**Comment by clauseggers** [comment]
Okay, then it must be something with the newest Tumbleweed because I get:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print(s.get('https://facebook.com/'))
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 21] Is a directory
```

I will take it up with them.

**Comment by untitaker** [comment]
@clauseggers any updates?

**Comment by clauseggers** [comment]
I posted on the Tumbleweed board, but no response. Next step is to open a ticket, might do that tomorrow if I hear nothing.

**Comment by untitaker** [comment]
Pretty sure you can go a more direct way and open a ticket, against the python-requests package if possible.

**Comment by clauseggers** [comment]
I have opened a ticket here:
https://bugzilla.opensuse.org/show_bug.cgi?id=937123

**Comment by untitaker** [comment]
@clauseggers Could you try setting the following options in vdirsyncer:

    verify = /dev/null
    verify_fingerprint = [fingerprint for server]

**Comment by untitaker** [comment]
I'm closing this for now because it's not an issue with vdirsyncer.

**Comment by clauseggers** [comment]
The verify_fingerprint has the effect of throwing an exception and failing. I tried both on iCloud and Facebook servers.

Anyhoot... I see that it just got patched, so I'll just wait for that to trickle down to Tumbleweed.
