### ISSUE TITLE
Cleartext password in config-file

### ISSUE THREAD

**Issue by nielsk** [untitaker/vdirsyncer#226]
Is there any way to call a command to put my password into an encrypted file?
For example in mbsync (a fast replacement for the slow and memory-hungry offlineimap) I can use instead of the password the following: gpg -q --for-your-eyes-only --no-tty -d /home/nik/.passwd/account.passwd.gpg

**Comment by untitaker** [comment]
Yes, see https://vdirsyncer.readthedocs.org/en/stable/keyring.html
