### ISSUE TITLE
Deprecate/discourage various forms of password storage?

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#228]
E.g. `netrc` is just as insecure as storing the password in the config file, and I can't see any advantages in using it.

**Comment by nblock** [comment]
One "advantage" is that the password only needs to be changed once, if a user/host is used multiple times.

**Comment by untitaker** [comment]
Right, at the point where this matters, a real password manager should be used IMO.

**Comment by geier** [comment]
If it isn't too much of a hassle to support those password storages I would leave them in but discourage from using them in the documentation. I believe there are still a lot of old school UNIXers out there who do use netrc files (netrc support was actually one of the first pull requests for pycarddav IIRC).

**Comment by nblock** [comment]
I think netrc support is quite useful for unatteded usage such as cron jobs. At least, the barrier is easier than eg. using a custom command and gpg to get the password.

**Comment by cyberic99** [comment]
What method woul you advise to use inside cron jobs, for instance?

**Comment by hobarrera** [comment]
Personally, I prefer to keep the password *outside* the config file, since I keep my dotfiles for my machines in sync via git on a public repository (plus, there's the sharing factor). I know this is a rather common practice too and I'd hate to have passwords in config files.

**Comment by untitaker** [comment]
I am not advocating for storing passwords inside config files, but storing them inside the .netrc is just as bad. Actually it's slightly worse since you now have a single insecure attack target. It is easy to write a small script that scans the user's PC for `.netrc` files. The same thing is not as easy to do with most password managers.

Ideally I'd like everybody to not store their credentials as plaintext files on their machines, but if you have a good reasons not to do that, you can still use the command-support from vdirsyncer to read from a plaintext file.

**Comment by hobarrera** [comment]
> I am not advocating for storing passwords inside config files, but storing them inside the .netrc is just as bad. Actually it's slightly worse since you now have a single insecure attack target. It is easy to write a small script that scans the user's PC for .netrc files. The same thing is not as easy to do with most password managers.

Most of my dotfiles are public, and if each app kept it's own password in-config, I'd be unable to share these.
Having a single separate file makes this simpler. Not that I'm merely talking about convenience there; there's extra security with either approach.

> Ideally I'd like everybody to not store their credentials as plaintext files on their machines, but if you have a good reasons not to do that, you can still use the command-support from vdirsyncer to read from a plaintext file.

The main problem is that we still *need* some way for vdirsyncer to know that password, many times unattended (I don't want some prompt from a cron job while playing/watching a movie!). It's a pretty hard problem, IMHO, since vdirsyncer actually *needs* the plain-text passwords.

**Comment by untitaker** [comment]
>It's a pretty hard problem, IMHO, since vdirsyncer actually needs the plain-text passwords.

The solution is either of those:

* Implement #24 
* Write a wrapper script that mimicks #24 (see discussion there)
* set the timeout of your master password long enough

**Comment by untitaker** [comment]
>Not that I'm merely talking about convenience there; there's extra security with either approach.

Storing the password in the dotfiles repo isn't just worse security -- it breaks security completely and shouldn't even be considered an option. Yes, using `.netrc` avoids that problem, but it's a too small step security-wise.

**Comment by untitaker** [comment]
To clarify, I consider `.netrc` to be more dangerous than anything else because it fixes only the most pressing security issues (not publishing your password with your config), but is still considered "secure enough" when it's not.

**Comment by hobarrera** [comment]
> set the timeout of your master password long enough

Keeping's GPG unlock with a higher cache sounds *a lot* riskier, since it actually opens the way to stealing *all* the passwords, not just my dav ones.

IMHO #24 is the way to go, though it would require unlocking on-boot.

**Comment by untitaker** [comment]
>Keeping's GPG unlock with a higher cache sounds a lot riskier, since it actually opens the way to stealing all the passwords, not just my dav ones.

Right, not the greatest option. It's what I currently use, but I want to get away from that.

**Comment by untitaker** [comment]
And yet storing your password in plaintext still turns out to be worse, because there is a risk left even if the machine is shut down.

**Comment by hobarrera** [comment]
> And yet storing your password in plaintext still turns out to be worse, because there is a risk left even if the machine is shut down.

This is covered by full-disk encryption in case of laptops/desktops. I don't think too many servers are running vdirsyncer, so the risk here is almost non-existent.

> Right, not the greatest option. It's what I currently use, but I want to get away from that.

Temporary workaround is to have a different gpg-key only for vdirsyncer's password, and keep *that* key unlocked indefinitely.

**Comment by untitaker** [comment]
Would you agree with removing netrc support if #24 was resolved?

**Comment by cyberic99** [comment]
I think you should give the users the ability to do what they want.
The .netrc support code is already there, so I would keep it as is.

**Comment by untitaker** [comment]
We've already had a similar discussion on principles -- basically my position is that we shouldn't assume that the user fully understands the consequences of their acts and will always choose the path of least resistance, and that even if they have installed ArchLinux (which is just copypasting commands anyway). This is also why `verify = False` is no longer possible in newer versions of vdirsyncer.

On 9 July 2015 23:51:03 CEST, cyberic99 <notifications@github.com> wrote:
>I think you should give the users the ability to do what they want.
>The .netrc support code is already there, so I would keep it as is.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120154480

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by geier** [comment]
Quoting Markus Unterwaditzer (2015-07-10 00:09:04)
> We've already had a similar discussion on principles -- basically my position is that we shouldn't assume that the user fully understands the consequences of their acts and will always choose the path of least resistance, and that even if they have installed ArchLinux (which is just copypasting commands anyway). This is also why `verify = False` is no longer possible in newer versions of vdirsyncer.

I still don't think that this is your responsibility. I also I am still
annoyed when I have to change a fingerprint (which happens rather often
at work since I get one calendar from an https only site with a
regularly changing, self-signed certificate.

>

**Comment by untitaker** [comment]
Regarding a warning in the docs, I have a slight feeling that nobody actually reads those and everybody just copy-pastes the example config. Of course this is not applicable in this situation since the possibility of using netrc or external commands is only mentioned in the docs, but I still wonder if a warning in the docs would even reach the people it was written for.

On 9 July 2015 23:51:03 CEST, cyberic99 <notifications@github.com> wrote:
>I think you should give the users the ability to do what they want.
>The .netrc support code is already there, so I would keep it as is.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120154480

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
I recieve weekly support requests where people have turned off cert verification because that was the easiest. Usually a borked installation of requests was at fault.

Note that you can pass paths to verify as well. If those certs have a common root, this is also an option. 

On 10 July 2015 00:16:40 CEST, Christian Geier <notifications@github.com> wrote:
>Quoting Markus Unterwaditzer (2015-07-10 00:09:04)
>> We've already had a similar discussion on principles -- basically my
>position is that we shouldn't assume that the user fully understands
>the consequences of their acts and will always choose the path of least
>resistance, and that even if they have installed ArchLinux (which is
>just copypasting commands anyway). This is also why `verify = False` is
>no longer possible in newer versions of vdirsyncer.
>
>I still don't think that this is your responsibility. I also I am still
>annoyed when I have to change a fingerprint (which happens rather often
>at work since I get one calendar from an https only site with a
>regularly changing, self-signed certificate.
>
>> 
>> On 9 July 2015 23:51:03 CEST, cyberic99 <notifications@github.com>
>wrote:
>> >I think you should give the users the ability to do what they want.
>> >The .netrc support code is already there, so I would keep it as is.
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120154480
>> 
>> -- 
>> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>>
>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120162294
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120163560

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Regarding responsibility, at the point where we begin to ask ourselves who was responsible for the damage done, it's already too late.

On 10 July 2015 00:16:40 CEST, Christian Geier <notifications@github.com> wrote:
>Quoting Markus Unterwaditzer (2015-07-10 00:09:04)
>> We've already had a similar discussion on principles -- basically my
>position is that we shouldn't assume that the user fully understands
>the consequences of their acts and will always choose the path of least
>resistance, and that even if they have installed ArchLinux (which is
>just copypasting commands anyway). This is also why `verify = False` is
>no longer possible in newer versions of vdirsyncer.
>
>I still don't think that this is your responsibility. I also I am still
>annoyed when I have to change a fingerprint (which happens rather often
>at work since I get one calendar from an https only site with a
>regularly changing, self-signed certificate.
>
>> 
>> On 9 July 2015 23:51:03 CEST, cyberic99 <notifications@github.com>
>wrote:
>> >I think you should give the users the ability to do what they want.
>> >The .netrc support code is already there, so I would keep it as is.
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120154480
>> 
>> -- 
>> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>>
>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120162294
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/228#issuecomment-120163560

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
>I also I am still annoyed when I have to change a fingerprint (which happens rather often at work since I get one calendar from an https only site with a regularly changing, self-signed certificate.

@geier I'd be really interested in whether `verify = /path/to/root` works for your usecase. I agree that your current situation is annoying, I wouldn't want to keep it that way.

**Comment by untitaker** [comment]
Scratching that idea for now.
