### ISSUE TITLE
Integrate Davical into testsuite

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#23]

**Comment by untitaker** [comment]
I wonder if there's a "unsafe" Postgres shim just for testing.

**Comment by untitaker** [comment]
I was told this is almost impossible.

I don't want to learn how to use postgres :(

**Comment by geier** [comment]
Well, on the plus side, davical support hasn't ever been broken IIRC. And I do believe it is one (if not *the*) most standard conform servers out there.

**Comment by untitaker** [comment]
>And I do believe it is one (if not the) most standard conform servers out there.

That's actually what I want to prove/disprove.
