### ISSUE TITLE
Remove setuptools-scm again

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#237]
Package maintainers (BSD) start to hardcode the version, presumably because they download the tarball instead of cloning from git.

**Comment by untitaker** [comment]
I have mixed feelings about this.

@0-wiz-0 Why does the [pkgsrc](http://pkgsrc.se/time/py-vdirsyncer) replace setuptools-scm?

**Comment by 0-wiz-0** [comment]
On Mon, Jul 20, 2015 at 02:46:17AM -0700, Markus Unterwaditzer wrote:
> I have mixed feelings about this.
> 
> @0-wiz-0 Why does the [pkgsrc](http://pkgsrc.se/time/py-vdirsyncer) replace setuptools-scm?

The commit message for this was (by joerg@NetBSD.org):

For Python 2.7, there is no such thing as setuptools_scm, so just
hard-code the number.

 Thomas

**Comment by untitaker** [comment]
setuptools-scm is an external dependency.

**Comment by 0-wiz-0** [comment]
On Mon, Jul 20, 2015 at 03:36:20AM -0700, Markus Unterwaditzer wrote:
> setuptools-scm is an external dependency.

Ok, patch in pkgsrc now replaced with dependency on that.
 Thomas

**Comment by untitaker** [comment]
Thanks!

I'll add a note to setup.py soon.

**Comment by untitaker** [comment]
@0-wiz-0 Sorry for calling it a dependency, I am actually not sure if it is one. It *seems* that it isn't installed or required when using PyPI tarballs, but is definetly used when installing from git master. In any case it's not a runtime dependency, it's required for installation at most.

**Comment by untitaker** [comment]
I've changed my mind again.
