### ISSUE TITLE
Add option to verify fingerprint and certificate chain

### ISSUE THREAD

**Issue by mathstuf** [untitaker/vdirsyncer#245]
It would be nice to verify both the chain and the fingerprint. AFAICT, checking the fingerprint does not check the expiration date of the remote certificate (seeing as I just went through and regenerated certs which were being accepted even though they expired in April).

**Comment by untitaker** [comment]
`verify_fingerprint` is currently also used in situations when the certificate is self-signed or somehow broken, yet otherwise the server supports SSL just fine.

I'm not sure how to allow this behavior without breaking this other usecase. Is this behavior really that useful?

**Comment by mathstuf** [comment]
Why use the cert chain at all in that case? If both are there, both should have to pass though.

**Comment by untitaker** [comment]
Because not everybody likes to or needs to pin by fingerprint. `verify_fingerprint` does disable the cert chain.

Also I imagine it's useful if you can use `verify = /path/to/custom` to pin against a particular set of certificates, or a particular CA (instead of all trusted CAs).

**Comment by mathstuf** [comment]
Maybe there's some confusion here. Currently there are 4 ways to go:

  - neither `verify` nor `verify_fingerprint` -> error ("nothing to check against, why are you doing SSL?")
  - `verify` without `verify_fingerprint` -> certificate checking
  - no `verify` with `verify_fingerprint` -> fingerprint checking
  - `verify` and `verify_fingerprint` -> fingerprint checking

I'm just asking that the last do both certificate and fingerprint checks.

**Comment by untitaker** [comment]
I understand. I assume that would also mean removing the behavior of automatically disabling `verify` if `verify_fingerprint` is set? Because otherwise we'd have to differentiate between "implicit verify" (no `verify` line in config) and "explicit verify" (`verify = True` in config), which is IMO confusing.

**Comment by untitaker** [comment]
Fixed.
