### ISSUE TITLE
sync with horde does not work

### ISSUE THREAD

**Issue by gfa** [untitaker/vdirsyncer#250]
neither calendar or contacts

this is the error synchronizing contacts

```
debug: Normalized URL from '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/CeF28S0onecbKwqRC9n4pg3' to '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/CeF28S0onecbKwqRC9n4pg3'
warning: Skipping '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/CeF28S0onecbKwqRC9n4pg3', etag property is missing.
debug: Normalized URL from '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/h0asGBUwVQQ9qdlLB9x_fQ2' to '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/h0asGBUwVQQ9qdlLB9x_fQ2'
warning: Skipping '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/h0asGBUwVQQ9qdlLB9x_fQ2', etag property is missing.
Unhandled exception occured for 000main.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 116, in prepare_idents
    raise SyncError('Etag changed during sync.')
SyncError: Etag changed during sync.
``` 

this is the error synchronizing the calendar

```
debug: Normalized URL from '/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/KguqpeuXqO1RPEEegAHvrME.ics' to '/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/KguqpeuXqO1RPEEegAHvrME.ics'
debug: Normalized URL from '/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/fkzZMMFV-J9y3tl4nGv_IfC.ics' to '/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/fkzZMMFV-J9y3tl4nGv_IfC.ics'
debug: Normalized URL from '/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/el9PwnCVKHc2UM1qOmNHwcu.ics' to '/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/el9PwnCVKHc2UM1qOmNHwcu.ics'
debug: Normalized URL from '/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/1SV-lXTkhWV8ood1SnUQhC0.ics' to '/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/1SV-lXTkhWV8ood1SnUQhC0.ics'
Unhandled exception occured for calendar.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 111, in prepare_idents
    if prefetch else ()):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line 387, in get_multi
    raise exceptions.NotFoundError(href)
NotFoundError: /rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/1SV-lXTkhWV8ood1SnUQhC0.ics

```
looks like the *Etag* is not working, whatever it is.  I did paste all log as it is big, looks like it can list all my contacts and calendar entries.

if i take one of the calendar entries and put as url in config this is the output

```
debug: Using 1 maximal workers.
Detected change in config file, discovering collections for calendar
Discovering collections for pair calendar
Syncing calendar
debug: Loaded status for calendar
debug: PROPFIND https://tk.zumbi.com.ar/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
debug: 207
debug: {'content-length': '371', 'content-encoding': 'gzip', 'set-cookie': 'Horde=enqoesrpua9mrd6gk8jrucbh81; path=/; domain=tk.zumbi.com.ar; HttpOnly, horde_secret_key=PyjkLv7GZMAaasdaZ_E; path=/; domain=tk.zumbi.com.ar; httponly, default_horde_view=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=tk.zumbi.com.ar', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary': 'Brief,Prefer,Accept-Encoding', 'keep-alive': 'timeout=5, max=99', 'server': 'Apache/2.2.22 (Debian)', 'dav': '1, 3, extended-mkcol, calendar-access, calendar-proxy, addressbook, 2, access-control, calendarserver-principal-property-search', 'connection': 'Keep-Alive', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Wed, 29 Jul 2015 14:41:24 GMT', 'x-powered-by': 'PHP/5.4.41-0+deb7u1', 'content-type': 'application/xml; charset=utf-8'}
debug: <?xml version="1.0" encoding="utf-8"?>
debug: <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics</d:href><d:propstat><d:prop><d:resourcetype/><d:getcontenttype>text/calendar; charset=utf-8</d:getcontenttype><d:getetag>"09edb3ee670b26482f88388ebc4ee17f"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
debug: Normalized URL from '/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics' to '/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics'
debug: Normalized URL from '/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics' to '/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics'
Unhandled exception occured for calendar.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 111, in prepare_idents
    if prefetch else ()):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line 387, in get_multi
    raise exceptions.NotFoundError(href)
NotFoundError: /rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics
```
i'm using 0.5.2 and horde Address Book (turba) 4.2.7,  Calendar (kronolith) 4.2.8

**Comment by gfa** [comment]
if I configure one contact as url i get this
```
Detected change in config file, discovering collections for 000main
Discovering collections for pair 000main
Syncing 000main
debug: Loaded status for 000main
debug: PROPFIND https://tk.zumbi.com.ar/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1/
debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <D:resourcetype/>
debug:                     <D:getcontenttype/>
debug:                     <D:getetag/>
debug:                 </D:prop>
debug:             </D:propfind>
debug:             
debug: Sending request...
debug: 207
debug: {'content-length': '347', 'content-encoding': 'gzip', 'set-cookie': 'Horde=h7abpivbg5v52i643flsloprn3; path=/; domain=tk.zumbi.com.ar; HttpOnly, horde_secret_key=W0wZPtfiasdIpEaOA4E; path=/; domain=tk.zumbi.com.ar; httponly, default_horde_view=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=tk.zumbi.com.ar', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary': 'Brief,Prefer,Accept-Encoding', 'keep-alive': 'timeout=5, max=99', 'server': 'Apache/2.2.22 (Debian)', 'dav': '1, 3, extended-mkcol, calendar-access, calendar-proxy, addressbook, 2, access-control, calendarserver-principal-property-search', 'connection': 'Keep-Alive', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Wed, 29 Jul 2015 14:44:42 GMT', 'x-powered-by': 'PHP/5.4.41-0+deb7u1', 'content-type': 'application/xml; charset=utf-8'}
debug: <?xml version="1.0" encoding="utf-8"?>
debug: <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1</d:href><d:propstat><d:prop><d:resourcetype/><d:getcontenttype>text/x-vcard</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getetag/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
debug: Normalized URL from '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1' to '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1'
warning: Skipping '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1', etag property is missing.
debug: Normalized URL from '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1' to '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1'
debug: REPORT https://tk.zumbi.com.ar/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1/
debug: {'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <C:addressbook-multiget xmlns:D="DAV:"
debug:                     xmlns:C="urn:ietf:params:xml:ns:carddav">
debug:                 <D:prop>
debug:                     <D:getetag/>
debug:                     <C:address-data/>
debug:                 </D:prop>
debug:                 <D:href>/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1</D:href>
debug:             </C:addressbook-multiget>
debug: Sending request...
debug: 207
debug: {'content-length': '317', 'content-encoding': 'gzip', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary': 'Brief,Prefer,Accept-Encoding', 'keep-alive': 'timeout=5, max=98', 'server': 'Apache/2.2.22 (Debian)', 'connection': 'Keep-Alive', 'pragma': 'no-cache', 'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'date': 'Wed, 29 Jul 2015 14:44:43 GMT', 'x-powered-by': 'PHP/5.4.41-0+deb7u1', 'content-type': 'application/xml; charset=utf-8'}
debug: <?xml version="1.0" encoding="utf-8"?>
debug: <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1</d:href><d:propstat><d:prop><d:getetag/><card:address-data/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
debug: Normalized URL from '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1' to '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1'
warning: Skipping '/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/a3od5zgMokI-JlFTjf86hA1', etag property is missing.
Unhandled exception occured for 000main.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 116, in prepare_idents
    raise SyncError('Etag changed during sync.')
SyncError: Etag changed during sync.
```

**Comment by untitaker** [comment]
Please try the master branch, it fixes many things regarding encodings (although I don't see how this would be an encoding issue).

If that doesn't help please mail me the full unabridged debug logs for sync in private, per mail.

On 29 July 2015 16:43:36 CEST, gustavo panizzo <notifications@github.com> wrote:
>neither calendar or contacts
>
>this is the error synchronizing contacts
>
>```
>debug: Normalized URL from
>'/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/CeF28S0onecbKwqRC9n4pg3'
>to
>'/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/CeF28S0onecbKwqRC9n4pg3'
>warning: Skipping
>'/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/CeF28S0onecbKwqRC9n4pg3',
>etag property is missing.
>debug: Normalized URL from
>'/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/h0asGBUwVQQ9qdlLB9x_fQ2'
>to
>'/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/h0asGBUwVQQ9qdlLB9x_fQ2'
>warning: Skipping
>'/rpc.php/turba/gfa@zumbi.com.ar/XM6crzOTfxHL-csFwqA_bA4/h0asGBUwVQQ9qdlLB9x_fQ2',
>etag property is missing.
>Unhandled exception occured for 000main.
>Traceback (most recent call last):
>File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77,
>in sync_collection
>    force_delete=force_delete
>File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in
>sync
>    b_info.prepare_idents(storage_a.read_only)
>File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 116, in
>prepare_idents
>    raise SyncError('Etag changed during sync.')
>SyncError: Etag changed during sync.
>``` 
>
>this is the error synchronizing the calendar
>
>```
>debug: Normalized URL from
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/KguqpeuXqO1RPEEegAHvrME.ics'
>to
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/KguqpeuXqO1RPEEegAHvrME.ics'
>debug: Normalized URL from
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/fkzZMMFV-J9y3tl4nGv_IfC.ics'
>to
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/fkzZMMFV-J9y3tl4nGv_IfC.ics'
>debug: Normalized URL from
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/el9PwnCVKHc2UM1qOmNHwcu.ics'
>to
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/el9PwnCVKHc2UM1qOmNHwcu.ics'
>debug: Normalized URL from
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/1SV-lXTkhWV8ood1SnUQhC0.ics'
>to
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/1SV-lXTkhWV8ood1SnUQhC0.ics'
>Unhandled exception occured for calendar.
>Traceback (most recent call last):
>File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77,
>in sync_collection
>    force_delete=force_delete
>File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in
>sync
>    b_info.prepare_idents(storage_a.read_only)
>File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 111, in
>prepare_idents
>    if prefetch else ()):
>File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line
>387, in get_multi
>    raise exceptions.NotFoundError(href)
>NotFoundError:
>/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/1SV-lXTkhWV8ood1SnUQhC0.ics
>
>```
>looks like the *Etag* is not working, whatever it is.  I did paste all
>log as it is big, looks like it can list all my contacts and calendar
>entries.
>
>
>if i take one of the calendar entries and put as url in config this is
>the output
>
>```
>debug: Using 1 maximal workers.
>Detected change in config file, discovering collections for calendar
>Discovering collections for pair calendar
>Syncing calendar
>debug: Loaded status for calendar
>debug: PROPFIND
>https://tk.zumbi.com.ar/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics/
>debug: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8',
>'User-Agent': 'vdirsyncer'}
>debug: <?xml version="1.0" encoding="utf-8" ?>
>debug:             <D:propfind xmlns:D="DAV:">
>debug:                 <D:prop>
>debug:                     <D:resourcetype/>
>debug:                     <D:getcontenttype/>
>debug:                     <D:getetag/>
>debug:                 </D:prop>
>debug:             </D:propfind>
>debug:             
>debug: Sending request...
>debug: 207
>debug: {'content-length': '371', 'content-encoding': 'gzip',
>'set-cookie': 'Horde=enqoesrpua9mrd6gk8jrucbh81; path=/;
>domain=tk.zumbi.com.ar; HttpOnly, horde_secret_key=PyjkLv7GZMAaasdaZ_E;
>path=/; domain=tk.zumbi.com.ar; httponly, default_horde_view=deleted;
>expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=tk.zumbi.com.ar',
>'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary':
>'Brief,Prefer,Accept-Encoding', 'keep-alive': 'timeout=5, max=99',
>'server': 'Apache/2.2.22 (Debian)', 'dav': '1, 3, extended-mkcol,
>calendar-access, calendar-proxy, addressbook, 2, access-control,
>calendarserver-principal-property-search', 'connection': 'Keep-Alive',
>'pragma': 'no-cache', 'cache-control': 'no-store, no-cache,
>must-revalidate, post-check=0, pre-check=0', 'date': 'Wed, 29 Jul 2015
>14:41:24 GMT', 'x-powered-by': 'PHP/5.4.41-0+deb7u1', 'content-type':
>'application/xml; charset=utf-8'}
>debug: <?xml version="1.0" encoding="utf-8"?>
>debug: <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"
>xmlns:cal="urn:ietf:params:xml:ns:caldav"
>xmlns:cs="http://calendarserver.org/ns/"
>xmlns:card="urn:ietf:params:xml:ns:carddav"><d:response><d:href>/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics</d:href><d:propstat><d:prop><d:resourcetype/><d:getcontenttype>text/calendar;
>charset=utf-8</d:getcontenttype><d:getetag>"09edb3ee670b26482f88388ebc4ee17f"</d:getetag></d:prop><d:status>HTTP/1.1
>200 OK</d:status></d:propstat></d:response></d:multistatus>
>debug: Normalized URL from
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics'
>to
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics'
>debug: Normalized URL from
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics'
>to
>'/rpc.php/calendars/gfa@zumbi.com.ar/calendar%7ETTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics'
>Unhandled exception occured for calendar.
>Traceback (most recent call last):
>File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 77,
>in sync_collection
>    force_delete=force_delete
>File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in
>sync
>    b_info.prepare_idents(storage_a.read_only)
>File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 111, in
>prepare_idents
>    if prefetch else ()):
>File "build/bdist.linux-x86_64/egg/vdirsyncer/storage/dav.py", line
>387, in get_multi
>    raise exceptions.NotFoundError(href)
>NotFoundError:
>/rpc.php/calendars/gfa@zumbi.com.ar/calendar~TTs_N04IVMGeFEmXkWiDfA3/wRt500qhsOqtTaMea6DI0A5.ics
>```
>i'm using 0.5.2 and horde Address Book (turba) 4.2.7,  Calendar
>(kronolith) 4.2.8 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/250

-- 
Sent from my phone. Please excuse my brevity.

**Comment by gfa** [comment]
On Wed, Jul 29, 2015 at 09:52:45AM -0700, Markus Unterwaditzer wrote:
> Please try the master branch, it fixes many things regarding encodings (although I don't see how this would be an encoding issue).

using master brach as 0.5.3.dev56+ng9229d08 works
