### ISSUE TITLE
Suggestion: when sync to missing calendar, error msg or mention in docs

### ISSUE THREAD

**Issue by rvdse** [untitaker/vdirsyncer#256]
I have a local filesystem storage for a calendar, and a DaviCal server running on apache 2.4, accessible only over TLS, with a self-signed certificate. When I first set up vdirsyncer to sync the local calendar to the server, I had not yet created a calendar on the server to sync to. I thought the calendar might be created; it wasnt -fair enough.

But the error messages I got (at least when trying over TLS) did not help me find the problem. When using the option verify_fingerprint I got the error: 
SSLError: <unprintable SSLError object>

When using verify = "X.pem", I got:
TypeError: cafile must be None or a byte string

And the same as above but without quotation marks, finally
NotFoundError: Not Found

I suppose these errors come from the requests library and it might not be possible to tell an SSL error apart from a missing calendar from outside the library(?), but I spend a few hours enabling older and older SSL protocols and making new certificates before I found the error.

I suggest mentioning in the docs that a caldav calendar must exist before syncing to it and perhaps in a troubleshooting section as well. Additionally, if possible, specific error messages for missing calendars.

**Comment by untitaker** [comment]
I'm not sure if Davical supports the kind of requests necessary to do this, but in principle vdirsyncer should ask whether to create missing calendars.

The SSL errors are not a result of the missing calendars, it's an unrelated problem that has to be fixed first. The TypeError should never happen though. Which Python version are you using?

Could you post the full debug log for the NotFoundError, and also show your pair configuration?

On 27 August 2015 20:39:49 CEST, rvdse <notifications@github.com> wrote:
>I have a local filesystem storage for a calendar, and a DaviCal server
>running on apache 2.4, accessible only over TLS, with a self-signed
>certificate. When I first set up vdirsyncer to sync the local calendar
>to the server, I had not yet created a calendar on the server to sync
>to. I thought the calendar might be created; it wasnt -fair enough.
>
>But the error messages I got (at least when trying over TLS) did not
>help me find the problem. When using the option verify_fingerprint I
>got the error: 
>SSLError: <unprintable SSLError object>
>
>When using verify = "X.pem", I got:
>TypeError: cafile must be None or a byte string
>
>And the same as above but without quotation marks, finally
>NotFoundError: Not Found
>
>I suppose these errors come from the requests library and it might not
>be possible to tell an SSL error apart from a missing calendar from
>outside the library(?), but I spend a few hours enabling older and
>older SSL protocols and making new certificates before I found the
>error.
>
>I suggest mentioning in the docs that a caldav calendar must exist
>before syncing to it and perhaps in a troubleshooting section as well.
>Additionally, if possible, specific error messages for missing
>calendars.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/256

-- 
Sent from my phone. Please excuse my brevity.

**Comment by rvdse** [comment]
Sure, I just assumed the missing calendar was to blame when it suddenly started working.

I use debian stable, so that is python 2.7.9-1 and 3.4.2-2 installed. I retraced my steps with this config (I removed domain, user and password).

```
[general]
status_path = ~/.vdirsyncer/status/

[pair course1_loc2davical]
a = course1_local
b = course1_davical
conflict_resolution = a wins

[storage course1_davical]
type = caldav
url = https://cal.X.se/caldav.php/X/test/
# Only one of the lines below uncommented at a time.
verify_fingerprint = "81:69:45:D8:50:8E:71:78:DE:50:2A:57:62:91:E7:70:8E:C7:16:BD"
#verify_fingerprint = 81:69:45:D8:50:8E:71:78:DE:50:2A:57:62:91:E7:70:8E:C7:16:BD
#verify = "/home/vdirsync/cal.X.pem"
#verify = /home/vdirsync/cal.X.pem

[storage course1_local]
type = filesystem
path = "~/testcal/"
fileext = .ics
```

Before I created the calendar called test on the server, using the verify_fingerprint lines (same result with and without quotation marks) gave the following error:

```
Unhandled exception occured for course1_loc2davical.
Traceback (most recent call last):
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
    force_delete=force_delete
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 760, in list
    for x in DavStorage.list(self):
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 569, in list
    headers=headers)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 326, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
SSLError: <unprintable SSLError object>
```

Changing to verify = cert.pem (without quotation) gave:

```
Unhandled exception occured for course1_loc2davical.
Traceback (most recent call last):
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
    force_delete=force_delete
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 760, in list
    for x in DavStorage.list(self):
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 569, in list
    headers=headers)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 326, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 96, in request
    raise exceptions.NotFoundError(r.reason)
NotFoundError: Not Found
```

And adding quotation marks around the path:

```
Unhandled exception occured for course1_loc2davical.
Traceback (most recent call last):
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
    force_delete=force_delete
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 760, in list
    for x in DavStorage.list(self):
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 569, in list
    headers=headers)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 326, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 237, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 263, in ssl_wrap_socket
    ctx.load_verify_locations(ca_certs, None)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 303, in load_verify_locations
    raise TypeError("cafile must be None or a byte string")
TypeError: cafile must be None or a byte string
```

Then I created the calendar on the server. The config using verify = cert (without quotes) worked and that's where I quit last time. This time I checked the other three lines after having created the calendar, and they all gave the same error as before.

**Comment by untitaker** [comment]
Could you send the full output with `-vdebug` option to me per email?

On 28 August 2015 23:21:09 CEST, rvdse <notifications@github.com> wrote:
>Sure, I just assumed the missing calendar was to blame when it suddenly
>started working.
>
>I use debian stable, so that is python 2.7.9-1 and 3.4.2-2 installed. I
>retraced my steps with this config (I removed domain, user and
>password).
>
>```
>[general]
>status_path = ~/.vdirsyncer/status/
>
>[pair course1_loc2davical]
>a = course1_local
>b = course1_davical
>conflict_resolution = a wins
>
>[storage course1_davical]
>type = caldav
>url = https://cal.X.se/caldav.php/X/test/
># Only one of the lines below uncommented at a time.
>verify_fingerprint =
>"81:69:45:D8:50:8E:71:78:DE:50:2A:57:62:91:E7:70:8E:C7:16:BD"
>#verify_fingerprint =
>81:69:45:D8:50:8E:71:78:DE:50:2A:57:62:91:E7:70:8E:C7:16:BD
>#verify = "/home/vdirsync/cal.X.pem"
>#verify = /home/vdirsync/cal.X.pem
>
>[storage course1_local]
>type = filesystem
>path = "~/testcal/"
>fileext = .ics
>```
>
>Before I created the calendar called test on the server, using the
>verify_fingerprint lines (same result with and without quotation marks)
>gave the following error:
>
>```
>Unhandled exception occured for course1_loc2davical.
>Traceback (most recent call last):
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py",
>line 65, in sync_collection
>    force_delete=force_delete
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py",
>line 163, in sync
>    b_info.prepare_idents(storage_a.read_only)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py",
>line 98, in prepare_idents
>    for href, etag in self.storage.list():
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 760, in list
>    for x in DavStorage.list(self):
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 569, in list
>    headers=headers)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 326, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py",
>line 79, in request
>    r = func(method, url, **kwargs)
>File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457,
>in request
>    resp = self.send(prep, **send_kwargs)
>File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569,
>in send
>    r = adapter.send(request, **kwargs)
>File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420,
>in send
>    raise SSLError(e, request=request)
>SSLError: <unprintable SSLError object>
>```
>
>Changing to verify = cert.pem (without quotation) gave:
>
>```
>Unhandled exception occured for course1_loc2davical.
>Traceback (most recent call last):
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py",
>line 65, in sync_collection
>    force_delete=force_delete
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py",
>line 163, in sync
>    b_info.prepare_idents(storage_a.read_only)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py",
>line 98, in prepare_idents
>    for href, etag in self.storage.list():
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 760, in list
>    for x in DavStorage.list(self):
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 569, in list
>    headers=headers)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 326, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py",
>line 96, in request
>    raise exceptions.NotFoundError(r.reason)
>NotFoundError: Not Found
>```
>
>And adding quotation marks around the path:
>
>```
>Unhandled exception occured for course1_loc2davical.
>Traceback (most recent call last):
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py",
>line 65, in sync_collection
>    force_delete=force_delete
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py",
>line 163, in sync
>    b_info.prepare_idents(storage_a.read_only)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/sync.py",
>line 98, in prepare_idents
>    for href, etag in self.storage.list():
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 760, in list
>    for x in DavStorage.list(self):
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 569, in list
>    headers=headers)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py",
>line 326, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File
>"/home/vdirsync/.local/lib/python2.7/site-packages/vdirsyncer/utils/http.py",
>line 79, in request
>    r = func(method, url, **kwargs)
>File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457,
>in request
>    resp = self.send(prep, **send_kwargs)
>File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569,
>in send
>    r = adapter.send(request, **kwargs)
>File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362,
>in send
>    timeout=timeout
>File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line
>516, in urlopen
>    body=body, headers=headers)
>File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line
>304, in _make_request
>    self._validate_conn(conn)
>File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line
>724, in _validate_conn
>    conn.connect()
>File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line
>237, in connect
>    ssl_version=resolved_ssl_version)
>File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py",
>line 263, in ssl_wrap_socket
>    ctx.load_verify_locations(ca_certs, None)
>File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 303, in
>load_verify_locations
>    raise TypeError("cafile must be None or a byte string")
>TypeError: cafile must be None or a byte string
>```
>
>Then I created the calendar on the server. The config using verify =
>cert (without quotes) worked and that's where I quit last time. This
>time I checked the other three lines after having created the calendar,
>and they all gave the same error as before.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/256#issuecomment-135890240

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Resolved in private.
