### ISSUE TITLE
jorani / ics feed support

### ISSUE THREAD

**Issue by gawel** [untitaker/vdirsyncer#263]
Hi,

I'm using vdirsyncer combined with khal for a while and I love them both.

My company has swith to https://github.com/bbalet/jorani to manage days off. The only feed available in this sofware is a ics url. Do you think there is a way to use that with vdirsyncer ?

**Comment by untitaker** [comment]
Yes, use the http storage type.

On 4 September 2015 18:26:38 CEST, Gael Pasgrimaud <notifications@github.com> wrote:
>Hi,
>
>I'm using vdirsyncer combined with khal for a while and I love them
>both.
>
>My company has swith to https://github.com/bbalet/jorani to manage days
>off. The only feed available in this sofware is a ics url. Do you think
>there is a way to use that with vdirsyncer ?
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/263

-- 
Sent from my phone. Please excuse my brevity.

**Comment by gawel** [comment]
Just works. Thanks a lot.
