### ISSUE TITLE
metasync does not coerce CDATA sections to strings

### ISSUE THREAD

**Issue by cstrahan** [untitaker/vdirsyncer#268]
`vdirsyncer` fails to sync my metadata:

    λ vdirsyncer --verbosity DEBUG metasync
    debug: Using 1 maximal workers.
    Metasyncing personal_contacts/Default
    debug: PROPFIND https://carddav.messagingengine.com/dav/addressbooks/user/cstrahan@fastmail.com/Default/
    debug: {'Depth': 0, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    debug: <?xml version="1.0" encoding="utf-8" ?>
    debug:             <D:propfind xmlns:D="DAV:">
    debug:                 <D:prop>
    debug:                     <ns0:displayname xmlns:ns0="DAV:"/>
    debug:                 </D:prop>
    debug:             </D:propfind>
    debug:
    debug: Sending request...
    debug: 207
    debug: {'content-length': '361', 'vary': 'Accept-Encoding, Brief, Prefer', 'server': 'nginx', 'connection': 'keep-alive', 'date': 'Wed, 16 Sep 2015 17:13:11 GMT', 'content-type': 'application/xml; charset=utf-8'}
    debug: <?xml version="1.0" encoding="utf-8"?>
    debug: <D:multistatus xmlns:D="DAV:">
    debug:   <D:response>
    debug:     <D:href>/dav/addressbooks/user/cstrahan@fastmail.com/Default/</D:href>
    debug:     <D:propstat>
    debug:       <D:prop>
    debug:         <D:displayname><![CDATA[Default]]></D:displayname>
    debug:       </D:prop>
    debug:       <D:status>HTTP/1.1 200 OK</D:status>
    debug:     </D:propstat>
    debug:   </D:response>
    debug: </D:multistatus>
    debug: Key: displayname
    debug: A: None
    debug: B: Default
    debug: S: None
    Copying displayname to personal_contacts_local/Default
    Unhandled exception occured for personal_contacts/Default.
    Traceback (most recent call last):
      File "/nix/store/p3mmy6nv3z4kb3pvnm7kzqrr3v2hj1q5-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 129, in metasync_collection
        keys=pair_options.get('metadata', None) or ()
      File "/nix/store/p3mmy6nv3z4kb3pvnm7kzqrr3v2hj1q5-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/metasync.py", line 49, in metasync
        _b_to_a()
      File "/nix/store/p3mmy6nv3z4kb3pvnm7kzqrr3v2hj1q5-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/metasync.py", line 22, in _b_to_a
        storage_a.set_meta(key, b)
      File "/nix/store/p3mmy6nv3z4kb3pvnm7kzqrr3v2hj1q5-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/storage/filesystem.py", line 195, in set_meta
        assert isinstance(value, text_type)
    AssertionError
    
My guess is that this is because the `displayname` property is returned in a CDATA section, and thus the value is not a string, but the respective CDATA type from the XML lib you're using. If I'm wrong, feel free to rename the issue title according the the actual problem.

**Comment by cstrahan** [comment]
I misunderstood. The property is a `str`, but it needs to be a of type `unicode` (this on python 2.7). I just tried with python 3, and I'm not seeing this problem.

Should we, perhaps, attempt a string conversion in `get_meta` (in `vdirsyncer/storage/dav.py`)?

**Comment by untitaker** [comment]
>Should we, perhaps, attempt a string conversion in get_meta (in vdirsyncer/storage/dav.py)?

It should definetly return a unicode string. I think it's fixed in master.

I also thought this was because of CDATA, but lxml actually returns native strings if the string fits into ASCII.

**Comment by untitaker** [comment]
@cstrahan Could you verify whether this is fixed for you?

**Comment by cstrahan** [comment]
@untitaker Just tested master with Python 2.7; it appears to be working:

    λ vdirsyncer metasync
    Metasyncing personal_contacts/Default
    Metasyncing personal_calendar/77fd5b5d-5e49-4d1d-939a-28202f14608c
    Metasyncing personal_calendar/8103e4ee-bc2e-4a39-a0b8-5c16bdd9e5f7
    Copying displayname to personal_calendar_local/77fd5b5d-5e49-4d1d-939a-28202f14608c

Thanks!

**Comment by untitaker** [comment]
Okay, thanks for reporting this!
