### ISSUE TITLE
XML_PARSE_HUGE & etag property is missing

### ISSUE THREAD

**Issue by digitalpixies** [untitaker/vdirsyncer#273]
Connecting to davmail w/ Exchange 2007

When I set davmail to limit to 90 days (and 1000) vdirsyncer syncs fine. but when i set it a higher number or 0 to push all my calendar throughI encounter an error about the xml being too big. I am unable to figure out how to enable the XML_PARSE_HUGE parameter.

A bunch of "etag property is missing" and "item content is missing" after the error message.

<pre>
warning: Partially invalid XML response, some of your items may be corrupted. Check the debug log and consider switching servers. (<string>:3607:329:FATAL:PARSER:ERR_INTERNAL_ERROR: Excessive depth in document: 256 use XML_PARSE_HUGE option
warning: <string>:3607:329:FATAL:PARSER:ERR_INTERNAL_ERROR: internal error: detected an error in element content
warning: 
warning: <string>:3607:329:FATAL:PARSER:ERR_DOCUMENT_END: Extra content at the end of the document)
warning: Skipping '/users/username@domainname.local/calendar/abc%20def%27s%20Birthday.EML', etag property is missing.
warning: Skipping /users/username@domainname.local/calendar/abc%20def%27s%20Birthday.EML, the item content is missing.
</pre>

**Comment by untitaker** [comment]
Hello Robert,

The error message talks about excessive depth. I assume this means that the response DavMail gives is a highly nested XML document.

However, the nesting level (depth) shouldn't change with the amount of calendar events. I suspect you're hitting http://sourceforge.net/p/davmail/bugs/598/

To verify this, run vdirsyncer with `-vdebug`, you might see similarly nested response tags.

On 21 September 2015 08:29:43 CEST, Robert <notifications@github.com> wrote:
>Closed #273.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/273#event-414435157

-- 
Sent from my phone. Please excuse my brevity.

**Comment by digitalpixies** [comment]
Hi Markus,

My issue appears to be related. At least I confirmed there’s some sort of problems pulling the xml data from davmail. It seems to be from some set of calendars from 2011 that are linked and referenced using curly bracket guids. Seems like davmail is having problems with those.

I also read your blog on the matter with webdav/carddav/caldav. I agree, it’s painful to use. I struggle with similar issues with webservice/soap and restful apis.

Keep up the great work.

Regards,
Robert Huie
