### ISSUE TITLE
Question about .netrc/keyring

### ISSUE THREAD

**Issue by nielsk** [untitaker/vdirsyncer#278]
Hi,

I finally wanted to move passwords out of my config-file and looked into the documentation for vdirsyncer but it is totally unclear to me what I actually have to use for my case.

The [.netrc](https://vdirsyncer.readthedocs.org/en/stable/keyring.html#netrc) states
```
machine someFQDN
login user
password somepass
```

The [keyring](https://vdirsyncer.readthedocs.org/en/stable/keyring.html#system-keyring) says:
```
vdirsyncer:someFQDN
```

I have several calendars I use via caldav.
They have the attributes:
```
[storage some_calendar_remote]
type = caldav
auth = guess
url = https://p01-caldav.icloud.com/99999999/calendars/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXX/
username = mymail@address.org
password = mycleartextpass
```
What would the .netrc or keyring-entry look like? What do I have to use as the machine-name? The URL? And then I leave the url in the entry and remove username and password? Or is it just p01-caldav.icloud.com I have to use as machine name?

Btw. you do not support an external command like [offlineimap does](https://wiki.archlinux.org/index.php/Mutt#Passwords_management), do you?

**Comment by untitaker** [comment]
Whatever I'll respond with will be irrelevant for the next version, where everything changes.

Look at `docs/keyring.rst` in the repo for the behavior the current master implements. Hopefully this new behavior is easier to understand.

On 6 October 2015 16:42:57 CEST, "Niels Kobschätzki" <notifications@github.com> wrote:
>Hi,
>
>I finally wanted to move passwords out of my config-file and looked
>into the documentation for vdirsyncer but it is totally unclear to me
>what I actually have to use for my case.
>
>The
>[.netrc](https://vdirsyncer.readthedocs.org/en/stable/keyring.html#netrc)
>states
>```
>machine someFQDN
>login user
>password somepass
>```
>
>The
>[keyring](https://vdirsyncer.readthedocs.org/en/stable/keyring.html#system-keyring)
>says:
>```
>vdirsyncer:someFQDN
>```
>
>I have several calendars I use via caldav.
>They have the attributes:
>```
>[storage some_calendar_remote]
>type = caldav
>auth = guess
>url =
>https://p01-caldav.icloud.com/99999999/calendars/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXX/
>username = mymail@address.org
>password = mycleartextpass
>```
>What would the .netrc or keyring-entry look like? What do I have to use
>as the machine-name? The URL? And then I leave the url in the entry and
>remove username and password? Or is it just p01-caldav.icloud.com I
>have to use as machine name?
>
>Btw. you do not support an external command like [offlineimap
>does](https://wiki.archlinux.org/index.php/Mutt#Passwords_management),
>do you?
>
>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/278

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Master docs are also available when selecting "latest" in the version selector in the bottom left corner of the docs. Password fetching docs for master: https://vdirsyncer.readthedocs.org/en/latest/keyring.html

**Comment by nielsk** [comment]
Thanks a lot; I wait for the next version. And then I will experiment how a script would have to look to get the password from a gpg-encrypted file
