### ISSUE TITLE
prompt is broken through echo

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#279]
cont #233.

This is an issue in click-threading.

**Comment by untitaker** [comment]
@eolianoe Could you try with the master version of `click-threading`?

**Comment by untitaker** [comment]
https://github.com/click-contrib/click-threading/commit/172a708d1379f6fb5e780abd1eafdedfb8fa5f2f

**Comment by eolianoe** [comment]
This is working nicely, all the prompts and displays are coming in the right order. For your question in #233 if I remember well, this behaviour was introduced with click-threading, so click-contrib/click-threading@172a708, seems to fix this behaviour.

**Comment by untitaker** [comment]
Released new version of click-threading.
