### ISSUE TITLE
Deleting contacts on local & have remote reflect that

### ISSUE THREAD

**Issue by kaihendry** [untitaker/vdirsyncer#280]
Not sure if this is related to #127, however what I am trying to do is delete duplicates locally and have those deletions reflect back on my carddav addressbook.

<img src=http://s.natalian.org/2015-10-12/deleting-contacts.png>

After deleting contacts and running sync, what I assumed would happen is the deleted contacts locally would make the remote contacts also delete. Instead what happended is that they synced down again.

I read the docs and _I think_ I need to uncomment `#collections = ["from b"]` to make it a little more balanced. But then vdirsyncer quits with: 

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: ...` ... I'm not sure if that's a permission error or... any ideas?

**Comment by untitaker** [comment]
Yes, you definetly  need to use the collections parameter. Please post a full traceback.

**Comment by kaihendry** [comment]
Ummm, how do I specify the collections parameter to reflect local changes onto remote?

I don't get a traceback unless I comment out the collections parameter.

**Comment by untitaker** [comment]
The collections parameter is not what you think it is. A collection may be an addressbook or calendar or tasklist. The collections parameter defines which collections get synchronized in the first place. Contact deletions/updates/creations are always considered from both sides, unless you are dealing with storages that can't be written to (http storage type).

Without the collections parameter, the URL you provide to the carddav storage is assumed to be a direct one to your addressbook (which means in most cases that it has the addressbook name in the URL). This is just not the case with your config.

The error you experience might come from your URL being "too specific". Try the ones from the documentation: https://vdirsyncer.readthedocs.org/en/stable/supported.html#fastmail If that one doesn't work, please post the output of `vdirsyncer -vdebug discover`. The output shouldn't contain secret information (it contains addressbook names and username, but no passwords or actual contacts), but please check anyway.

**Comment by untitaker** [comment]
@kaihendry any update on this?

**Comment by kaihendry** [comment]
With `vdirsyncer -vdebug discover` I did notice a difference in the URLs:

    https://carddav.messagingengine.com/dav/principals/user/hendry@webconverger.com/
    https://carddav.messagingengine.com/dav/addressbooks/user/hendry@webconverger.com/

But tbh, I went back and forth and it didn't seem to change anything. In fact, bizarrely everything seems to work as expected now.

Sidenote: Do you know of any scripts to detect duplicate vcfs and then merge them?

**Comment by untitaker** [comment]
Hello Kai,

Unfortunately such a script doesn't exist, at least not that I'd know.

On 28 October 2015 06:56:52 CET, Kai Hendry <notifications@github.com> wrote:
>With `vdirsyncer -vdebug discover` I did notice a difference in the
>URLs:
>
>https://carddav.messagingengine.com/dav/principals/user/hendry@webconverger.com/
>https://carddav.messagingengine.com/dav/addressbooks/user/hendry@webconverger.com/
>
>But tbh, I went back and forth and it didn't seem to change anything.
>In fact, bizarrely everything seems to work as expected now.
>
>Sidenote: Do you know of any scripts to detect duplicate vcfs and then
>merge them?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/280#issuecomment-151733792

-- 
Sent from my phone. Please excuse my brevity.
