### ISSUE TITLE
Invalid [general] section as of 0.7.0

### ISSUE THREAD

**Issue by hobarrera** [untitaker/vdirsyncer#286]
I'm getting the following as of 0.7.0:

```
$ vdirsyncer -v DEBUG sync    
critical: Error during reading config /home/hugo/.config/vdirsyncer/config: Invalid general section. You should copy the example config from the repository and edit it: https://github.com/untitaker/vdirsyncer
```

Here's my config:

```
cat /home/hugo/.config/vdirsyncer/config

[general]
status_path = ~/.local/share/vdirsyncer/status/
password_command = ~/.local/bin/vdirsyncer-pass

##### Contacts ######

[pair contacts]
a = local
b = radicale
metadata = ["color", "displayname"]

[storage local]
type = filesystem
path = ~/.local/share/contacts/cards/
fileext = .vcf

[storage radicale]
type = carddav
url = https://calendar.barrera.io/hugo/addressbook.vcf/
username = hugo

##### Calendar: Study ######

[pair study]
a = study_local
b = study_fastmail
metadata = ["color", "displayname"]

[storage study_local]
type = filesystem
path = ~/.local/share/calendars/study/
fileext = .ics

[storage study_fastmail]
type = caldav
url = https://caldav.messagingengine.com/dav/calendars/user/hobarrera@fastmail.com/9bcef3fa-504d-4c6f-b320-fd24257de5a7/
username = hobarrera@fastmail.com

##### Calendar: Personal ######

[pair personal]
a = personal_local
b = personal_fastmail
metadata = ["color", "displayname"]

[storage personal_local]
type = filesystem
path = ~/.local/share/calendars/personal/
fileext = .ics

[storage personal_fastmail]
type = caldav
url = https://caldav.messagingengine.com/dav/calendars/user/hobarrera@fastmail.com/502708f4-4b94-4963-b042-f7340c829bdf/
username = hobarrera@fastmail.com

##### Calendar: Work ######

[pair work]
a = work_local
b = work_fastmail
metadata = ["color", "displayname"]

[storage work_local]
type = filesystem
path = ~/.local/share/calendars/work/
fileext = .ics

[storage work_fastmail]
type = caldav
url = https://caldav.messagingengine.com/dav/calendars/user/hobarrera@fastmail.com/d6aa4f1e-bdf6-4b6b-999d-b89afd62c994/
username = hobarrera@fastmail.com

```

This used to work fine on 0.6.0, and I'm not seeing any documented changes on 0.7.0.

**Comment by hobarrera** [comment]
Oh, I found [the commit](https://github.com/untitaker/vdirsyncer/commit/3a4e4218a60fa2ffa81b90748d8ac40bad76775a) that changed this. [The docs](https://vdirsyncer.readthedocs.org/en/stable/config.html#general-section) seem to be out of date.

**Comment by untitaker** [comment]
password_command is gone. I didn't know the error message is that bad though.

On 28 October 2015 07:56:06 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I'm getting the following as of 0.7.0:
>
>```
>$ vdirsyncer -v DEBUG sync    
>critical: Error during reading config
>/home/hugo/.config/vdirsyncer/config: Invalid general section. You
>should copy the example config from the repository and edit it:
>https://github.com/untitaker/vdirsyncer
>```
>
>Here's my config:
>
>
>```
>cat /home/hugo/.config/vdirsyncer/config
>
>[general]
>status_path = ~/.local/share/vdirsyncer/status/
>password_command = ~/.local/bin/vdirsyncer-pass
>
>##### Contacts ######
>
>[pair contacts]
>a = local
>b = radicale
>metadata = ["color", "displayname"]
>
>[storage local]
>type = filesystem
>path = ~/.local/share/contacts/cards/
>fileext = .vcf
>
>[storage radicale]
>type = carddav
>url = https://calendar.barrera.io/hugo/addressbook.vcf/
>username = hugo
>
>##### Calendar: Study ######
>
>[pair study]
>a = study_local
>b = study_fastmail
>metadata = ["color", "displayname"]
>
>[storage study_local]
>type = filesystem
>path = ~/.local/share/calendars/study/
>fileext = .ics
>
>[storage study_fastmail]
>type = caldav
>url =
>https://caldav.messagingengine.com/dav/calendars/user/hobarrera@fastmail.com/9bcef3fa-504d-4c6f-b320-fd24257de5a7/
>username = hobarrera@fastmail.com
>
>##### Calendar: Personal ######
>
>[pair personal]
>a = personal_local
>b = personal_fastmail
>metadata = ["color", "displayname"]
>
>[storage personal_local]
>type = filesystem
>path = ~/.local/share/calendars/personal/
>fileext = .ics
>
>[storage personal_fastmail]
>type = caldav
>url =
>https://caldav.messagingengine.com/dav/calendars/user/hobarrera@fastmail.com/502708f4-4b94-4963-b042-f7340c829bdf/
>username = hobarrera@fastmail.com
>
>##### Calendar: Work ######
>
>[pair work]
>a = work_local
>b = work_fastmail
>metadata = ["color", "displayname"]
>
>[storage work_local]
>type = filesystem
>path = ~/.local/share/calendars/work/
>fileext = .ics
>
>[storage work_fastmail]
>type = caldav
>url =
>https://caldav.messagingengine.com/dav/calendars/user/hobarrera@fastmail.com/d6aa4f1e-bdf6-4b6b-999d-b89afd62c994/
>username = hobarrera@fastmail.com
>
>```
>
>This used to work fine on 0.6.0, and I'm not seeing any documented
>changes on 0.7.0.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/286

-- 
Sent from my phone. Please excuse my brevity.

**Comment by hobarrera** [comment]
> password_command is gone. I didn't know the error message is that bad though.

Yup. I mostly left this open because the docs are partially out-of-date too, so it's hard to find the issue.

**Comment by untitaker** [comment]
Oh, I missed that. Yikes. Should I release a new version?

**Comment by hobarrera** [comment]
I'm not sure. Do you need to in order to update rtd? Specifically, the configuration section makes no mention of the change: https://vdirsyncer.readthedocs.org/en/stable/config.html#general-section

**Comment by untitaker** [comment]
Yeah the docs only show the changes for the latest version. This is usually useful since e.g. the docs for the new password fetching have been in master for months, yet they aren't on the page because the latest version doesn't have that behavior.
