### ISSUE TITLE
"When do I need Vdirsyncer" lists only advantages of git vs. vdirsyncer

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/vdirsyncer#287]
The documentation at https://vdirsyncer.readthedocs.org/en/stable/when.html gives no advantage of vdirsyncer compared to git. So, the question "When do I need Vdirsyncer" is not answered.

**Comment by untitaker** [comment]
It's a badly worded page overall, but the main thing I had in mind is to give the user some ideas. It's obvious that Git won't allow you to sync with iCloud or FastMail.
