### ISSUE TITLE
keyring.rst: where is the url passed

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/vdirsyncer#288]
The documentation is not clear about how to pass parameters to the command when using `password.fetch`

**Comment by untitaker** [comment]
This line in https://vdirsyncer.readthedocs.org/en/stable/keyring.html seems pretty clear to me:

    password.fetch = ["command", "~/get-password.sh", "more", "args"]

**Comment by DamienCassou** [comment]
Sorry, I was thinking about something else. You are right, your doc is perfect.
