### ISSUE TITLE
Exception in thread Thread

### ISSUE THREAD

**Issue by smu** [untitaker/vdirsyncer#291]
I run vdirsyncer against an owncloud caldav server regularily using cron. From time to time (approx every 10th sync) I get the following exception:

```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/home/smu/cal/vdirsyncer_env/local/lib/python2.7/site-packages/click_threading/__init__.py", line 33, in run
  File "/home/smu/cal/vdirsyncer_env/local/lib/python2.7/site-packages/click/core.py", line 302, in __exit__
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```
Seems to be similar to  #167.

 - vdirsyncer, version 0.7.0
 - Install with pip in virtualenv, as desribed in the manual.

Do you need any further information?

**Comment by untitaker** [comment]
Yeah, please dump `pip freeze` here.

**Comment by smu** [comment]
Here you go:

```
argparse==1.2.1
atomicwrites==0.1.8
click==5.1
click-log==0.1.1
click-threading==0.1.2
configobj==5.0.6
distribute==0.6.24
icalendar==3.9.1
keepassc==1.6.2
khal==v0.6.1.dev194-ng1d709dc
lxml==3.5.0b1
pkginfo==1.2.1
python-dateutil==2.4.2
pytz==2015.7
pyxdg==0.25
requests==2.8.1
requests-toolbelt==0.4.0
six==1.10.0
tzlocal==1.2
urwid==1.3.1
vdirsyncer==0.7.0
wsgiref==0.1.2
```

**Comment by untitaker** [comment]
Should be fixed in master. Could you try installing vdirsyncer with `pip install git+https://github.com/untitaker/vdirsyncer`? If pip thinks it doesn't need to do anything, do `pip uninstall vdirsyncer` and try again.

**Comment by smu** [comment]
Ok, I installed the github version and will report if the Exception occurs again.

**Comment by smu** [comment]
No further exceptions since three days, so I guess the problem is solved. thank you.

**Comment by untitaker** [comment]
Alright, thanks for reporting this!
