### ISSUE TITLE
double vdirsyncer requests

### ISSUE THREAD

**Issue by dlaquintana** [untitaker/vdirsyncer#293]
Hi,
How can i avoid these double vdirsyncer requests ?

for USER None and USER Daniela 

could you help me ?
Thanks a lot

2015-10-30 11:26:16,305 - INFO: REPORT request at /daniela.ics/ received
2015-10-30 11:26:16,305 - DEBUG: Request headers:
{'CONTENT_LENGTH': '642',
 'CONTENT_TYPE': 'application/xml; charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': '192.168.8.190:5232',
 'HTTP_USER_AGENT': 'vdirsyncer',
 'PATH_INFO': '/daniela.ics/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.8.190',
 'REMOTE_HOST': 'PC-OMASERVER.imteam.local',
 'REQUEST_METHOD': 'REPORT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'PC-OMASERVER.imteam.local',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.8',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x000000000054A150>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x00000000026084C8>,
 'wsgi.input': <socket._fileobject object at 0x0000000002E5F4F8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-10-30 11:26:16,315 - DEBUG: Sanitized path: /daniela.ics/
2015-10-30 11:26:16,315 - DEBUG: USER None
2015-10-30 11:26:16,315 - DEBUG: Request content:
<?xml version="1.0" encoding="utf-8" ?>
            <C:calendar-query xmlns:D="DAV:"
                xmlns:C="urn:ietf:params:xml:ns:caldav">
                <D:prop>
                    <D:getcontenttype/>
                    <D:getetag/>
                </D:prop>
                <C:filter>
                
                <C:comp-filter name="VCALENDAR">
                    <C:comp-filter name="VTODO">
                        <C:time-range start="20141030T000000Z" end="20251027T000000Z"/>
                    </C:comp-filter>
                </C:comp-filter>
                
                </C:filter>
            </C:calendar-query>
2015-10-30 11:26:16,315 - DEBUG: USER None
2015-10-30 11:26:16,315 - INFO: Anonymous user refused
2015-10-30 11:26:16,315 - DEBUG: Answer status: 401 Unauthorized
2015-10-30 11:26:16,315 - INFO: REPORT request at /daniela.ics/ received
2015-10-30 11:26:16,325 - DEBUG: Request headers:
{'CONTENT_LENGTH': '642',
 'CONTENT_TYPE': 'application/xml; charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': 'Basic ZGFuaWVsYTpkYW5pZWxh',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': '192.168.8.190:5232',
 'HTTP_USER_AGENT': 'vdirsyncer',
 'PATH_INFO': '/daniela.ics/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.8.190',
 'REMOTE_HOST': 'PC-OMASERVER.imteam.local',
 'REQUEST_METHOD': 'REPORT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'PC-OMASERVER.imteam.local',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.8',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x000000000054A150>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x00000000026084C8>,
 'wsgi.input': <socket._fileobject object at 0x0000000002E5F4F8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-10-30 11:26:16,325 - DEBUG: Sanitized path: /daniela.ics/
2015-10-30 11:26:16,325 - DEBUG: USER daniela

**Comment by untitaker** [comment]
That's normal HTTP auth. Setting `auth = basic` helps with this.

**Comment by dlaquintana** [comment]
Thanks !

________________________________
Da: Markus Unterwaditzer [mailto:notifications@github.com]
Inviato: 16 November 2015 22:26
A: untitaker/vdirsyncer
Cc: Daniela Laquintana
Oggetto: Re: [vdirsyncer] double vdirsyncer requests (#293)


Closed #293<https://github.com/untitaker/vdirsyncer/issues/293>.

-
Reply to this email directly or view it on GitHub<https://github.com/untitaker/vdirsyncer/issues/293#event-465963617>.
-- This message has been checked by ESVA and is believed to be clean.
