### ISSUE TITLE
 10061 The connection has been refused by the remote host (10061)

### ISSUE THREAD

**Issue by dlaquintana** [untitaker/vdirsyncer#294]
Hi,
I'm using radicale as Carddav server
and sometimes I obtain the error 10061
I've installed requests-2.5.0 lib

```
Syncing teamquality_gfuselli_impegni
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\teamquality_aziende.items from 666 to 600
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\teamquality_impegni.items from 666 to 600
Syncing teamquality_aspinelli_impegni
Syncing siatec_lceri_impegni
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\siatec_pbrignoli_impegni.items from 666 to 600
Syncing teamquality_mrota_impegni
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\teamquality_gfuselli_impegni.items from 666 to 600
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\teamquality_aspinelli_impegni.items from 666 to 600
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\siatec_lceri_impegni.items from 666 to 600
warning: Correcting permissions of C:\Users\Administrator\.vdirsyncer\status\teamquality_mrota_impegni.items from 666 to 600
Unhandled exception occured for teamquality_gfuselli_impegni.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\vdirsyncer\cli\tasks.py", line 65, in sync_collection
    force_delete=force_delete
  File "C:\Python27\lib\site-packages\vdirsyncer\sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "C:\Python27\lib\site-packages\vdirsyncer\sync.py", line 98, in prepare_idents
    for href, etag in self.storage.list():
  File "C:\Python27\lib\site-packages\vdirsyncer\storage\dav.py", line 785, in list
    headers=headers)
  File "C:\Python27\lib\site-packages\vdirsyncer\storage\dav.py", line 326, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "C:\Python27\lib\site-packages\vdirsyncer\utils\http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10061, 'Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))
Copying (uploading) item 040000008200E00074C5B7101A82E00800000000509DDCA06A20D10100000000000000001000000011C7B54C6F15FE4EAE9CC87399B9353B to siatec_lceri_impegni_tqdav
```

do you have any suggestions for me?
they are very useful
best regards

**Comment by untitaker** [comment]
In general vdirsyncer isn't officially supported on Windows. Be careful, and do backups.

* This path: `C:\Users\Administrator.vdirsyncer` Do you literally have a user called `Administrator.vdirsyncer`? Or is a slash missing?
* Search for the item `040000008200E00074C5B7101A82E00800000000509DDCA06A20D10100000000000000001000000011C7B54C6F15FE4EAE9CC87399B9353B` in your local calendars, using some sort of full-text search (no idea what to do on Windows) How large is it?
* Is there anything in the server logs? Perhaps the server crashed?

**Comment by dlaquintana** [comment]
- a slash is missing...the user name is administrator

- 040000008200E00074C5B7101A82E00800000000509DDCA06A20D10100000000000000001000000011C7B54C6F15FE4EAE9CC87399B9353B is a UID created by Exchange for a VEVENT item

- in the radicale server log i've found two type of errors

Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 653, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 712, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 279, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10054] Connessione in corso interrotta forzatamente dall'host remoto

Traceback (most recent call last):
  File "C:\Python27\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Users\Administrator\Desktop\Progetti\tQdav\src\radicale\__init__.py", line 311, in __call__
    is_authenticated = auth.is_authenticated(user, password)
  File "C:\Users\Administrator\Desktop\Progetti\tQdav\src\radicale\auth\tqsia_auth.py", line 91, in is_authenticated
    req1 = requests.post(URL, data=payload1)
  File "C:\Python27\lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10061, 'Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))



some times 




C:\Users\Administrator\.vdirsyncer\status\teamquality_aziende.items from 666 to 600

**Comment by untitaker** [comment]
How large is the item file?

**Comment by dlaquintana** [comment]
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Rome
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY;LANGUAGE=it-IT:da daniela.ics a sia e da sia a daniela.ics\n[Fuori se
 de]
DTSTART;TZID="Europe/Rome":20150902T090000
DTEND;TZID="Europe/Rome":20150902T100000
UID:040000008200E00074C5B7101A82E00800000000B9E960F04BE5D00100000000000000001
 00000007C92D70E3CAD1347B733A96598D5E8BD
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20150903T072452Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:0
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:2113477620
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR

about 1.089 byte...

**Comment by dlaquintana** [comment]
it's only an example

**Comment by dlaquintana** [comment]
...
Copying (uploading) item 040000008200E00074C5B7101A82E00800000000509DDCA06A20D10100000000000000001000000011C7B54C6F15FE4EAE9CC87399B9353B to siatec_lceri_impegni_tqdav
...
the item is uploaded to storage siatec_lceri_impegni_tqdav 
and this upload is working fine
the exception occured for storage  teamquality_gfuselli_impegni
it's late...
I'm sorry,
I don't understand your question
"How large is the item file?"

**Comment by dlaquintana** [comment]
Good morning,
more details...
when vdirsyncer gets the exception on a storage, the radicale server is running (it's not crashed)
I suppose that it's just a bit more slow (msec) in response, because there are other incoming requests
is there any solution to solve the problem ?
thanks a lot

**Comment by untitaker** [comment]
I don't think there's a solution. If the connection has been refused, there's little vdirsyncer can do. Check if any other programs (such as firewall or antivirus) block vdirsyncer, although I wonder why that would happen only sometimes.

**Comment by untitaker** [comment]
@dlaquintana I'm not sure how to resolve this problem. As said, I suspect there is no solutions. Independent of that I'd strongly recommend not to use the combination of Radicale and Windows.

**Comment by dlaquintana** [comment]
I've solved the problem, thanks
probably it was the only solution in this context....

With only one radicale server and many pairs to synchronize in the vdirsyncer config file,
the error 10061 The connection has been refused by the remote host (10061)
was quite frequent
With two radicale servers 
(on which I subdivide the requests)
the error reported by vdirsyncer has disappeared
best regards
