### ISSUE TITLE
Jorani/ICS Feed

### ISSUE THREAD

**Issue by yukiology** [untitaker/vdirsyncer#296]
Hi,
Good day. First of all I'm not really expert in server and network, nor PHP. Recently I just done setting up Jorani for my company and all run smoothly but just with 1 thing. When I trying to use ICS to connect it to my google calendar, its not working. I tried to open the link ICS given in Jorani and it end up Server Error 500. 

My question is, do I need to do any configuration to enable the ICS ? Or allow some port from my firewall ( currently is port 80 for Jorani) ?

**Comment by geier** [comment]
I think you probably wanted to post this in [jorani](https://github.com/bbalet/jorani)'s [tracker](https://github.com/bbalet/jorani/issues)?

**Comment by untitaker** [comment]
Yes, please file this in their tracker. I have no idea about Jorani.

**Comment by yukiology** [comment]
Sorry I mistaken the thread..
