### ISSUE TITLE
Print non-error output to stdout

### ISSUE THREAD

**Issue by pheerai** [untitaker/vdirsyncer#297]
Currently, I get the following output:

```
$ vdirsyncer2 sync
Syncing private_calendar/personal
```

As this is the expected behaviour, I'd like to dump the output using `vdirsyncer2 sync > /dev/null`, but this still prints the output.

`vdirsyncer2 sync 2> /dev/null` does the job, but won't notify when something went wrong.

It would be nice to:
 - either have a `verbosity` option that affects the logging level,
 - or send the "Syncing {}"-string to stdout instead of stderr

**Comment by untitaker** [comment]
There is a verbosity setting, but it has to be specified before `sync` because it's a global option. See `vdirsyncer --help` (not `vdirsyncer sync --help`).

Agreed on second point, it's something that has to be fixed in [click-log](https://pypi.python.org/pypi/click-log/0.1.1). Rather low priority to me though. If enough users ask I'll get around to it, probably, maybe?

**Comment by untitaker** [comment]
This is fixed with https://github.com/click-contrib/click-log/commit/2a12c9164770b43c448015bf308eabffefb8ee01 and the release of `click-log==0.1.2`.

**Comment by untitaker** [comment]
And click-log 0.1.3 is out to include warnings in stderr...

**Comment by lockywolf** [comment]
I am using the last vdirsyncer, and status messages are going to stderr, not stdout. 

```
~/bin/lwf_check_contacts_calendars.bash 1> /dev/null
Discovering collections for pair lockywolf_contacts
lockywolf_contacts_local:
  - "default" ("Address Book")
lockywolf_contacts_remote:
  - "default" ("Address Book")
Saved for lockywolf_contacts: collections = ["default"]
Metasyncing lockywolf_contacts/default
Syncing lockywolf_contacts/default
```

I am running vdirsyncer from cron, and by convention cron scripts usually discard stdout, and report stderr. 
This can be worked around by setting a proper log level, but still, would it be possible to only receive errors into the stderr?

For the sake of completeness, the script is very simple:

```
printf "Running vdirsyncer discover\n"
if ! vdirsyncer discover
then
    printf "Vdirsyncer discover failed!\n" 1>&2
fi
printf "\n"
printf "Running vdirsyncer metasync\n"
if ! vdirsyncer  metasync
then
    printf "Vdirsyncer metasync failed!\n" 1>&2
fi
printf "\n"
printf "Running vdirsyncer sync\n"
if ! vdirsyncer sync
then
    printf "Vdirsyncer sync failed!\n" 1>&2
fi
```
