### ISSUE TITLE
Sync fails with critical error suggesting requests-toolbelt should be > 0.4.0, but 0.5.0 installed

### ISSUE THREAD

**Issue by theamma** [untitaker/vdirsyncer#301]
$ pip install --user --upgrade vdirsyncer
Requirement already up-to-date: vdirsyncer in /usr/local/lib/python2.7/dist-packages
Cleaning up...
$ python --version
Python 2.7.6
$ pip install --user --upgrade vdirsyncer
Requirement already up-to-date: vdirsyncer in /usr/local/lib/python2.7/dist-packages
Cleaning up...
$ vdirsyncer --verbosity=DEBUG sync
debug: Using 1 maximal workers.
Discovering collections for pair martin_calendar
critical: Failed to initialize martin_calendar_remote
critical:   - Your version of requests_toolbelt is too old for `guess` authentication. At least version 0.4.0 is required.
$ pip show requests-toolbelt
Name: requests-toolbelt
Version: 0.5.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests

Distribution is  Linux Mint 17.2 "Rafaela"

Thanks, 
Martin

**Comment by untitaker** [comment]
Can you try:

    $ python
    >>> from requests_toolbelt.auth.guess import GuessAuth

**Comment by theamma** [comment]
Hi unitaker
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests_toolbelt.auth.guess import GuessAuth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/ssl.py", line 14, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/_compat.py", line 20, in <module>
    from urllib3 import connection
ImportError: cannot import name connection
>>>
```
seems like urlib3 causes the problem?
```
> pip show urllib3
---
Name: urllib3
Version: 1.7.1
Location: /usr/lib/python2.7/dist-packages
Requires: 
```
As a workaround, man may set `auth = basic` explicit in config file ~/.config/vdirsyncer/config

**Comment by untitaker** [comment]
Ah yes, this is a debian problem again. See https://vdirsyncer.readthedocs.org/en/stable/problems.html
