### ISSUE TITLE
ascii decoding error

### ISSUE THREAD

**Issue by hobarrera** [untitaker/vdirsyncer#311]
```
Unhandled exception occured for personal.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 58, in sync_collection
    force_delete=force_delete
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 181, in sync
    action(a_info, b_info, conflict_resolution)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 203, in inner
    dest_href, dest_etag = dest.storage.upload(item)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 17, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 485, in upload
    return self._put(href, item, None)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 463, in _put
    headers=headers
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 322, in request
    return utils.http.request(method, url, session=self._session, **more)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/utils/http.py", line 79, in request
    r = func(method, url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 447, in prepare_body
    body = self._encode_params(data)
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 84, in _encode_params
    return to_native_string(data)
  File "/usr/lib/python3.5/site-packages/requests/utils.py", line 700, in to_native_string
    out = string.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 288: ordinal not in range(128)
Syncing personal
Syncing contacts
Syncing study
Syncing work
Copying (uploading) item PNPPDGRG4PI5YK5JVJPLUSKNO30CZXJ1M185 to personal_fastmail
```

I'm not entirely sure what file triggered the error, however, all runs after that, showed a conflict (while this is the only machine that syncs with this storage, so I'm guessing there may have been some sort of mis-sync?):

```
error: personal: One item changed on both sides. Resolve this conflict manually, or by setting the `conflict_resolution` parameter in your config file.
error: See also https://vdirsyncer.readthedocs.org/en/latest/api.html#pair-section
error: Item ID: L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON
error: Item href on side A: L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON.ics
error: Item href on side B: /dav/calendars/user/hobarrera@fastmail.com/502708f4-4b94-4963-b042-f7340c829bdf/L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON.ics
Syncing personal
Syncing contacts
Syncing work
Syncing study
Doing conflict resolution for item L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON...
```

On a side note, I've no idea how to manually resolve the conflict - is a diff, or anything alike left somewhere?

**Comment by untitaker** [comment]
You need to change your requests version to a version that is not 2.9.0 (it is explicitly blacklisted in setup.py). There was an issue open about this.

On 22 December 2015 22:06:44 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>```
>Unhandled exception occured for personal.
>Traceback (most recent call last):
>File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line
>58, in sync_collection
>    force_delete=force_delete
>File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 181,
>in sync
>    action(a_info, b_info, conflict_resolution)
>File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 203,
>in inner
>    dest_href, dest_etag = dest.storage.upload(item)
>File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py",
>line 17, in inner
>    return f(self, *args, **kwargs)
>File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py",
>line 17, in inner
>    return f(self, *args, **kwargs)
>File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line
>485, in upload
>    return self._put(href, item, None)
>File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line
>463, in _put
>    headers=headers
>File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line
>322, in request
>  return utils.http.request(method, url, session=self._session, **more)
>File "/usr/lib/python3.5/site-packages/vdirsyncer/utils/http.py", line
>79, in request
>    r = func(method, url, **kwargs)
>File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 454,
>in request
>    prep = self.prepare_request(req)
>File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 388,
>in prepare_request
>    hooks=merge_hooks(request.hooks, self.hooks),
>File "/usr/lib/python3.5/site-packages/requests/models.py", line 296,
>in prepare
>    self.prepare_body(data, files, json)
>File "/usr/lib/python3.5/site-packages/requests/models.py", line 447,
>in prepare_body
>    body = self._encode_params(data)
>File "/usr/lib/python3.5/site-packages/requests/models.py", line 84, in
>_encode_params
>    return to_native_string(data)
>File "/usr/lib/python3.5/site-packages/requests/utils.py", line 700, in
>to_native_string
>    out = string.decode(encoding)
>UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position
>288: ordinal not in range(128)
>Syncing personal
>Syncing contacts
>Syncing study
>Syncing work
>Copying (uploading) item PNPPDGRG4PI5YK5JVJPLUSKNO30CZXJ1M185 to
>personal_fastmail
>```
>
>I'm not entirely sure what file triggered the error, however, all runs
>after that, showed a conflict (while this is the only machine that
>syncs with this storage, so I'm guessing there may have been some sort
>of mis-sync?):
>
>```
>error: personal: One item changed on both sides. Resolve this conflict
>manually, or by setting the `conflict_resolution` parameter in your
>config file.
>error: See also
>https://vdirsyncer.readthedocs.org/en/latest/api.html#pair-section
>error: Item ID: L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON
>error: Item href on side A: L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON.ics
>error: Item href on side B:
>/dav/calendars/user/hobarrera@fastmail.com/502708f4-4b94-4963-b042-f7340c829bdf/L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON.ics
>Syncing personal
>Syncing contacts
>Syncing work
>Syncing study
>Doing conflict resolution for item
>L1BH6GK1P6UXK98QQK9GK5PVIOLIS8S9SOON...
>```
>
>On a side note, I've no idea how to manually resolve the conflict - is
>a diff, or anything alike left somewhere?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/311

-- 
Sent from my phone. Please excuse my brevity.

**Comment by hobarrera** [comment]
```
$ pip freeze | grep reque
requests==2.9.1
```

```
$ vdirsyncer sync
Syncing work
Syncing study
Syncing contacts
Syncing personal
Doing conflict resolution for item E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8...
error: personal: One item changed on both sides. Resolve this conflict manually, or by setting the `conflict_resolution` parameter in your config file.
error: See also https://vdirsyncer.readthedocs.org/en/latest/api.html#pair-section
error: Item ID: E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8
error: Item href on side A: E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8.ics
error: Item href on side B: /dav/calendars/user/hobarrera@fastmail.com/502708f4-4b94-4963-b042-f7340c829bdf/E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8.ics
```

Looks like the damage is done.  
How would one do the resolution manually?

**Comment by untitaker** [comment]
Manual resolution would mean manually editing the file on server and client to have the same content. There is also an issue open about better conflict resolution modes.

On 22 December 2015 22:32:54 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>```
>$ pip freeze | grep reque
>requests==2.9.1
>```
>
>```
>$ vdirsyncer sync
>Syncing work
>Syncing study
>Syncing contacts
>Syncing personal
>Doing conflict resolution for item
>E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8...
>error: personal: One item changed on both sides. Resolve this conflict
>manually, or by setting the `conflict_resolution` parameter in your
>config file.
>error: See also
>https://vdirsyncer.readthedocs.org/en/latest/api.html#pair-section
>error: Item ID: E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8
>error: Item href on side A: E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8.ics
>error: Item href on side B:
>/dav/calendars/user/hobarrera@fastmail.com/502708f4-4b94-4963-b042-f7340c829bdf/E21CZ6VZ01I0T1T2AWXXO1ENLRD4JFRLB0I8.ics
>```
>
>Looks like the damage is done.  
>How would one do the resolution manually?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/311#issuecomment-166735069

-- 
Sent from my phone. Please excuse my brevity.

**Comment by hobarrera** [comment]
Right, but, how do I get the file from the server to compare it? I'm not the administrator, so I don't have raw-fs access.

Should I set up a new vdirsyncer instance to sync to another directory and compare that?

**Comment by untitaker** [comment]
That's pretty much the problem. There is no straightforward way, and vdirsyncer will absolutely not help you. But the item is fetched during sync, so you can see the severside content in the debug log.

What I generally do is to just set the conflict_resolution param to the side that I think updates more often. I also check my data into git should I ever loose data that (or some other) way.

On 22 December 2015 22:57:30 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>Right, but, how do I get the file from the server to compare it? I'm
>not the administrator, so I don't have raw-fs access.
>
>Should I set up a new vdirsyncer instance to sync to another directory
>and compare that?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/311#issuecomment-166741132

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
#127 is the issue about conflict resolution modes. I think this issue can be closed?

**Comment by hobarrera** [comment]
I'll continue discussion on #127, thanks.
