### ISSUE TITLE
Kill keyring support

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#313]
See discussion on #302

**Comment by untitaker** [comment]
Quoting from previous thread:

>Tbh this is precisely why I am getting sick of keyring, it adds an opaque abstraction layer that doesn't make it obvious where stuff is actually stored. One advantage of custom CLI commands is that you can just try them out on the console to see if they work. You don't have a true equivalent with keyring, unless you consider the Python REPL. But if you're not a Python dev, that's not a good experience.

Turns out that the keyring lib comes with a CLI tool, so there's really nothing that warrants the special-casing in vdirsyncer. You can just do:

    password.fetch = ["command", "keyring", "example.com", "untitaker"]

and if you want to be more explicit about the password store to use, `keyring` has options for that (both for security and performance).

Any comments?

/cc @geier @jaraco @hobarrera

**Comment by hobarrera** [comment]
Given the mentioned cli tool, I don't see any point in including keyring support as a special-case. Just document the tool as one more choice for interested users and that's it.

I haven't used a vdirsyncer with keyring, personally. I see little use for it, since something that requires manual unlocking is not useful because this runs via cron for me (I suspect that's a really common scenario).

Honestly, I wish there were some way to secure the password, but I can't honestly think of any. Having a text file with it ends up being as secure as any other measure that will work via cron.

**Comment by untitaker** [comment]
I've created a PR at #320, but let's wait for other's feedback.

**Comment by geier** [comment]
:+1:

**Comment by untitaker** [comment]
I've just figured out that the `keyring` command also stores the password in a plaintext file if no system keyring can be found, without telling the user.

**Comment by jaraco** [comment]
I'm not sure I understand. I'm a little unfamiliar with vdirsyncer.

Is the intention of the command 'keyring', 'system', 'user' intended to invoke the command "keyring system user"? If so, that's not quite right - it would need to be "keyring get system user".

Also, keyring does currently use insecure backends when secure backends are not available. The only currently-open issue is intended to address that (not storing passwords in plaintext without explicit opt-in).

**Comment by jaraco** [comment]
I would also suggest you consider "python -m keyring get system user", which relies on Python 2.7, but is slightly more portable than relying on the executable.

**Comment by jaraco** [comment]
The real challenge with keyring is that it has dependencies on more than just the 'keyring' library. For Windows and OS X, keyring is sufficient for securely saving and retrieving passwords, but on Linux, it's more complicated. One needs pycrypto (with interactive input) or a service like kwallet or secretservice with its requisite libraries to be viable.

I hope that helps your project make better decisions about how keyring may or may not help.

Best - Jason

**Comment by untitaker** [comment]
>If so, that's not quite right - it would need to be "keyring get system user".

Yes, I've noticed and corrected the PR.

Thanks for your response. I'd wish that the keyring commandline utility would generally be more explicit or informative about where passwords are stored. `keyring set ...` may store your password *anywhere* (only on Linux of course). It's hard to detect what's going on, and whether my credentials are stored in the keyring I actually want. It doesn't even matter whether all possible backends are secure (though it's a good thing generally): It's more about knowing what keyring actually does.

Proposed solution would be to print the keyring that would be used, and perhaps ask for user confirmation. Or require that the user sets a backend via the CLI themselves.
