### ISSUE TITLE
Support sha256 certificate fingerprints

### ISSUE THREAD

**Issue by bastorran** [untitaker/vdirsyncer#321]
Hello,

most of modern browser plan to discard sha1 in the near future. So I think it would be a good idea to support sha256 certificate pinning in vdirsyncer as well. (If it is already implemented, it's not written in the documentation.)

Thank you four your work!

**Comment by untitaker** [comment]
SHA-1 certificates will be deprecated, i.e. if you cert is signed with SHA-1. Not SHA-1 fingerprints. You can generate a SHA-1 fingerprint for any certificate.

Of course SHA-256 fingerprint support would be nice anyway. @t-8ch is there a way to support that in requests-toolbelt?

**Comment by t-8ch** [comment]
@untitaker New kinds of fingerprints are handled directly by urllib3. (https://github.com/shazow/urllib3/blob/c6b7a16c067773ffbb6b96a76985e69e72d5acf9/urllib3/util/ssl_.py#L17)
With recent versions of requests (and its bundled urllib3) SHA256 should just work™
