### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by nielsk** [untitaker/vdirsyncer#323]
I installed now Fedora and just installed vdirsyncer. When I run vdirsyncer sync, I get for each calendar the following:

    File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
    force_delete=force_delete
    File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 155, in sync
    for ident, (href_a, etag_a, href_b, etag_b) in iteritems(status)
    File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 155, in <genexpr>
    for ident, (href_a, etag_a, href_b, etag_b) in iteritems(status)
    ValueError: need more than 2 values to unpack
    Unhandled exception occured for some_calendar.

Version is 0.6.0

**Comment by untitaker** [comment]
It seems that you switched from a newer version to an older one.

BTW only the very latest stable version of vdirsyncer is supported, all older ones are effectively unmaintained.

On 22 January 2016 14:09:39 CET, "Niels Kobschätzki" <notifications@github.com> wrote:
>I installed now Fedora and just installed vdirsyncer. When I run
>vdirsyncer sync, I get for each calendar the following:
>
>File "/usr/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line
>65, in sync_collection
>    force_delete=force_delete
>File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 155,
>in sync
>    for ident, (href_a, etag_a, href_b, etag_b) in iteritems(status)
>File "/usr/lib/python2.7/site-packages/vdirsyncer/sync.py", line 155,
>in <genexpr>
>    for ident, (href_a, etag_a, href_b, etag_b) in iteritems(status)
>    ValueError: need more than 2 values to unpack
>    Unhandled exception occured for some_calendar.
>
>Version is 0.6.0
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/323

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
The fix here is to upgrade to the latest version of vdirsyncer.

cc @mbaldessari, vdirsyncer is at 0.7.5

**Comment by mbaldessari** [comment]
I know, I have updated it, but there are two new dependencies that need packaging as well. Hence me being a bit behind with things

**Comment by nielsk** [comment]
thanks

**Comment by mbaldessari** [comment]
Ok I submitted package reviews for python-click-log and python-click-threading (BZ https://bugzilla.redhat.com/show_bug.cgi?id=1275860 will track the whole thing)

**Comment by untitaker** [comment]
:+1:

**Comment by mbaldessari** [comment]
@nielsk https://bodhi.fedoraproject.org/updates/FEDORA-2016-05ab2257b7 works for me, but testing is appreciated

**Comment by untitaker** [comment]
Thanks for all your work!

On 13 February 2016 09:40:13 CET, Michele Baldessari <notifications@github.com> wrote:
>@nielsk https://bodhi.fedoraproject.org/updates/FEDORA-2016-05ab2257b7
>works for me, but testing is appreciated
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/323#issuecomment-183625369

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nielsk** [comment]
@mbaldessari thanks - sorry for the late feedback. The package works for me :)
