### ISSUE TITLE
Allow to use Environment variables in local path directives

### ISSUE THREAD

**Issue by teto** [untitaker/vdirsyncer#329]
I would like to set my local caldav and carddav directories differently on each of my machine, with the help of environment variables.
For instance, I would like to write:
`path = $DG_DATA_HOME/calendars/perso`

**Comment by untitaker** [comment]
path.fetch = ["command", "sh", "-c", "echo $DG_DATA_HOME/calendars/perso"]

`x.fetch = ["command", ...]` executes a command and uses its output as value for `x`. See https://vdirsyncer.readthedocs.org/en/stable/keyring.html

**Comment by teto** [comment]
This is very cool. Thanks !

2016-02-04 21:41 GMT+01:00 Markus Unterwaditzer <notifications@github.com>:
