### ISSUE TITLE
Won't run from cron

### ISSUE THREAD

**Issue by benv666** [untitaker/vdirsyncer#335]
Hej there,

Not sure what's going wrong here, vdirsyncer runs fine from a terminal, but when I put it in cron it dies like this:
```
Traceback (most recent call last):
  File "/usr/bin/vdirsyncer", line 11, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/usr/lib64/python3.5/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: a bytes-like object is required, not 'str'
```
Vdirsyncer was installed through pip3 (systemwide).

**Comment by untitaker** [comment]
Could you pastebin the output of `env` in both those environments? (once run via cron, once via shell).

**Comment by benv666** [comment]
http://pastebin.com/G4BAM6eZ is from cron
http://pastebin.com/zmBpPuSt from a normal shell

**Comment by untitaker** [comment]
Alright, so you're probably missing all those `LC_`-variables, but most importantly `LANG`. I have no idea why and how it crashes *this* way though.

**Comment by benv666** [comment]
Check, once I added LANG it works. Thanks for the support!

**Comment by hobarrera** [comment]
I tried unsetting all the `LC_*` variables and `LANG` individually.

The lack of `LC_CTYPE` AND `LANG` triggered this error for me.

**Comment by untitaker** [comment]
Reopening, this should be fixed in Click.

**Comment by untitaker** [comment]
Ah, this is fixed on https://github.com/mitsuhiko/click/issues/494
