### ISSUE TITLE
Figure out what to do with Davical tests in "untrusted builds"

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#350]
See #348: Since hobarrera's PR may have contained malicious code that echoes those variables, they are not available there. Therefore the Davical tests crash.

Should we just skip the tests? It seems like the only thing we can do.

**Comment by hobarrera** [comment]
Huh? I did what?

Honestly, I don't even understand why that PR broke those tests. Did I screw up something bad, and I'm not even understanding what I did?

**Comment by untitaker** [comment]
No, nothing like that.

The tests against davical run against @geier's testserver, with a test account. The test account's credentials are set as environment variables `DAVICAL_USERNAME` and `DAVICALE_PASSWORD` using https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings. They are NOT set inside e.g. .travis.yml or elsewhere in the git repo because they're secret.

One could steal those secrets by opening a PR that contains `echo $DAVICAL_PASSWORD`, and then simply read the password from the Travis build log. In order to prevent that, the variables are apparently not available when the PR is from a branch of a fork.

**Comment by hobarrera** [comment]
Actually, are we sure PRs are run with those variables? Maybe that's why the build for mine failed?

**Comment by untitaker** [comment]
PRs whose base branches are on untitaker/vdirsyncer do have those variables.

**Comment by hobarrera** [comment]
What do you think about setting up a davical instance on one of the heroku free-tier instances. There seem to be instructions [here](https://github.com/drewbug/davical-heroku).

If you're interested in it, I can take a closer look at that later on (I've used heroku for a client, so am somewhat familiar).

If it works, we might be able to scale that to other servers too.

**Comment by untitaker** [comment]
I don't think that would fix anything TBH. It's just cost for additional servers. Christian's server is already there OTOH.

On 29 February 2016 14:42:07 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>What do you think about setting up a davical instance on one of the
>heroku free-tier instances. There seem to be instructions
>[here](https://github.com/drewbug/davical-heroku).
>
>If you're interested in it, I can take a closer look at that later on
>(I've used heroku for a client, so am somewhat familiar).
>
>If it works, we might be able to scale that to other servers too.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/350#issuecomment-190216224

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
> I don't think that would fix anything TBH. It's just cost for additional servers. Christian's server is already there OTOH.

I mean the free-tier server, which adds no cost. The difference is that we don't care if anybody has davical credentials to those, since they're used exclusively for tests (and we can wipe them completely at any time).

**Comment by untitaker** [comment]
I see... The credentials for the current server are not that critical either (also a test account), it's just a security measure to avoid somebody writing his disk full.

A separate server for testing would be a little safer, but the current setup has the advantage of coming with no administrative overhead.

On 29 February 2016 14:46:55 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>> I don't think that would fix anything TBH. It's just cost for
>additional servers. Christian's server is already there OTOH.
>
>I mean the free-tier server, which adds no cost. The difference is that
>we don't care if anybody has davical credentials to those, since
>they're used exclusively for tests (and we can wipe them completely at
>any time).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/350#issuecomment-190217571

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
With https://github.com/vdirsyncer/davical-testserver/commit/cce1273cc883f3cdb3ccf37097b29ac0263b7055 and https://github.com/vdirsyncer/davical-testserver/commit/783bcd7fac399e77c43fb71142f6ef589cd1bb00, credentials for @geier's testserver are now public.
