### ISSUE TITLE
Sync'ing color should not sync trailing newline

### ISSUE THREAD

**Issue by hobarrera** [untitaker/vdirsyncer#358]
I've my calendars configured with a `/color` file with a hex colour (eg: #c0c0c0). Since I edit these files with vim, they end up with a trailing newline. I doubt I'm the only person for whom this happens too.

When I sync to my CalDAV server, sync works fine, but other clients that sync to it (a web client, a mobile client) fail to parse this value, and use a fallback colour.

I've reported the issue to those other clients (since they can't be *that* strict in what the accept!), but I still think vdirsyncer should trim the trailing newline when uploading the colour.

**Comment by untitaker** [comment]
I don't think it's the other client's responsibility to accept such values.

**Comment by hobarrera** [comment]
FWIW, Fastmail fixed their consumer support too. :)

**Comment by untitaker** [comment]
I'm reopening this, the fix is terrible. `get_meta` should already return the normalized value, at least it should be this way in [python-vdir](https://github.com/vdirsyncer/python-vdir).
