### ISSUE TITLE
Make server builds fully reproducible

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#377]
I am thinking of including the server repositories at https://github.com/vdirsyncer in the form of git submodules, instead of cloning them.

Since submodules are always defining a commit hash, it would make reproducible builds possible: People presumably get the same test result if they check the same hash out.

Another idea would be to start inlining most repos into the main repo, but this would require that we slim down the ownCloud and Baikal repos quite a bit.

Opinions?

**Comment by hobarrera** [comment]
+1 submodules. It does exactly what you're after, and might also simplify the builds scripts a wee bit.
-1 to having them in the main repo. Seems to dirty IMHO.
