### ISSUE TITLE
Test against OS X

### ISSUE THREAD

**Issue by untitaker** [untitaker/vdirsyncer#379]
Cont #169 

I've failed at setting up a local OS X VM in VirtualBox.

**Comment by hobarrera** [comment]
I'd started working on this on my branch [case-insensitive-filesystem](https://github.com/hobarrera/vdirsyncer/commits/case-insensitive-filesystems), but never got it to work. You might like to use that as a starting point?

**Comment by untitaker** [comment]
Do you have Travis logs handy?

On 11 March 2016 16:24:27 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I'd started working on this on my branch
>[case-insensitive-filesystem](https://github.com/hobarrera/vdirsyncer/commits/case-insensitive-filesystems),
>but never got it to work. You might like to use that as a starting
>point?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/379#issuecomment-195412398

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
https://travis-ci.org/hobarrera/vdirsyncer/jobs/110787675

It requires more work on the build scripts as far as I could tell. My interest was quickly lost though, and I didn't get past that.

**Comment by hobarrera** [comment]
I mostly wanted to point out that this could be done quite easily in travis.

**Comment by untitaker** [comment]
I can't make any sense of the logs. I'll try later today.

On 11 March 2016 16:32:14 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>https://travis-ci.org/hobarrera/vdirsyncer/jobs/110787675
>
>It requires more work on the build scripts as far as I could tell. My
>interest was quickly lost though, and I didn't get past that.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/379#issuecomment-195416277

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
